/*
Pulp 3 API

Testing ContentBlobsAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package zest

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "github.com/content-services/zest/release/v2025"
)

func Test_zest_ContentBlobsAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test ContentBlobsAPIService ContentContainerBlobsList", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var pulpDomain string

		resp, httpRes, err := apiClient.ContentBlobsAPI.ContentContainerBlobsList(context.Background(), pulpDomain).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test ContentBlobsAPIService ContentContainerBlobsRead", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var containerBlobHref string

		resp, httpRes, err := apiClient.ContentBlobsAPI.ContentContainerBlobsRead(context.Background(), containerBlobHref).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test ContentBlobsAPIService ContentContainerBlobsSetLabel", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var containerBlobHref string

		resp, httpRes, err := apiClient.ContentBlobsAPI.ContentContainerBlobsSetLabel(context.Background(), containerBlobHref).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test ContentBlobsAPIService ContentContainerBlobsUnsetLabel", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var containerBlobHref string

		resp, httpRes, err := apiClient.ContentBlobsAPI.ContentContainerBlobsUnsetLabel(context.Background(), containerBlobHref).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
