/*
Pulp 3 API

Testing ContentOpenpgpSignatureAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package zest

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "github.com/content-services/zest/release/v2025"
)

func Test_zest_ContentOpenpgpSignatureAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test ContentOpenpgpSignatureAPIService ContentCoreOpenpgpSignatureList", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var pulpDomain string

		resp, httpRes, err := apiClient.ContentOpenpgpSignatureAPI.ContentCoreOpenpgpSignatureList(context.Background(), pulpDomain).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test ContentOpenpgpSignatureAPIService ContentCoreOpenpgpSignatureRead", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var openPGPSignatureHref string

		resp, httpRes, err := apiClient.ContentOpenpgpSignatureAPI.ContentCoreOpenpgpSignatureRead(context.Background(), openPGPSignatureHref).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
