/*
Pulp 3 API

Testing ApiDebugDomainorgBackfillReportAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package zest

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "github.com/content-services/zest/release/v2026"
)

func Test_zest_ApiDebugDomainorgBackfillReportAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test ApiDebugDomainorgBackfillReportAPIService ApiPulpDebugDomainorgBackfillReportGet", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		httpRes, err := apiClient.ApiDebugDomainorgBackfillReportAPI.ApiPulpDebugDomainorgBackfillReportGet(context.Background()).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test ApiDebugDomainorgBackfillReportAPIService ApiPulpDebugDomainorgBackfillReportPost", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.ApiDebugDomainorgBackfillReportAPI.ApiPulpDebugDomainorgBackfillReportPost(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
