/*
Pulp 3 API

Testing ContentguardsEnvvarHeaderAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package zest

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "github.com/content-services/zest/release/v2026"
)

func Test_zest_ContentguardsEnvvarHeaderAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test ContentguardsEnvvarHeaderAPIService ContentguardsCoreEnvvarHeaderAddRole", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var envVarHeaderContentGuardHref string

		resp, httpRes, err := apiClient.ContentguardsEnvvarHeaderAPI.ContentguardsCoreEnvvarHeaderAddRole(context.Background(), envVarHeaderContentGuardHref).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test ContentguardsEnvvarHeaderAPIService ContentguardsCoreEnvvarHeaderCreate", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var pulpDomain string

		resp, httpRes, err := apiClient.ContentguardsEnvvarHeaderAPI.ContentguardsCoreEnvvarHeaderCreate(context.Background(), pulpDomain).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test ContentguardsEnvvarHeaderAPIService ContentguardsCoreEnvvarHeaderDelete", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var envVarHeaderContentGuardHref string

		httpRes, err := apiClient.ContentguardsEnvvarHeaderAPI.ContentguardsCoreEnvvarHeaderDelete(context.Background(), envVarHeaderContentGuardHref).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test ContentguardsEnvvarHeaderAPIService ContentguardsCoreEnvvarHeaderList", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var pulpDomain string

		resp, httpRes, err := apiClient.ContentguardsEnvvarHeaderAPI.ContentguardsCoreEnvvarHeaderList(context.Background(), pulpDomain).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test ContentguardsEnvvarHeaderAPIService ContentguardsCoreEnvvarHeaderListRoles", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var envVarHeaderContentGuardHref string

		resp, httpRes, err := apiClient.ContentguardsEnvvarHeaderAPI.ContentguardsCoreEnvvarHeaderListRoles(context.Background(), envVarHeaderContentGuardHref).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test ContentguardsEnvvarHeaderAPIService ContentguardsCoreEnvvarHeaderMyPermissions", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var envVarHeaderContentGuardHref string

		resp, httpRes, err := apiClient.ContentguardsEnvvarHeaderAPI.ContentguardsCoreEnvvarHeaderMyPermissions(context.Background(), envVarHeaderContentGuardHref).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test ContentguardsEnvvarHeaderAPIService ContentguardsCoreEnvvarHeaderPartialUpdate", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var envVarHeaderContentGuardHref string

		resp, httpRes, err := apiClient.ContentguardsEnvvarHeaderAPI.ContentguardsCoreEnvvarHeaderPartialUpdate(context.Background(), envVarHeaderContentGuardHref).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test ContentguardsEnvvarHeaderAPIService ContentguardsCoreEnvvarHeaderRead", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var envVarHeaderContentGuardHref string

		resp, httpRes, err := apiClient.ContentguardsEnvvarHeaderAPI.ContentguardsCoreEnvvarHeaderRead(context.Background(), envVarHeaderContentGuardHref).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test ContentguardsEnvvarHeaderAPIService ContentguardsCoreEnvvarHeaderRemoveRole", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var envVarHeaderContentGuardHref string

		resp, httpRes, err := apiClient.ContentguardsEnvvarHeaderAPI.ContentguardsCoreEnvvarHeaderRemoveRole(context.Background(), envVarHeaderContentGuardHref).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test ContentguardsEnvvarHeaderAPIService ContentguardsCoreEnvvarHeaderUpdate", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var envVarHeaderContentGuardHref string

		resp, httpRes, err := apiClient.ContentguardsEnvvarHeaderAPI.ContentguardsCoreEnvvarHeaderUpdate(context.Background(), envVarHeaderContentGuardHref).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
