/*
Pulp 3 API

Testing NpmWhoamiAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package zest

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "github.com/content-services/zest/release/v2026"
)

func Test_zest_NpmWhoamiAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test NpmWhoamiAPIService NpmWhoamiGet", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var path string
		var pulpDomain string

		httpRes, err := apiClient.NpmWhoamiAPI.NpmWhoamiGet(context.Background(), path, pulpDomain).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
