/*
Pulp 3 API

Testing ContentViewsRpmEnvironmentsAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package zest

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "github.com/content-services/zest/release/v2026"
)

func Test_zest_ContentViewsRpmEnvironmentsAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test ContentViewsRpmEnvironmentsAPIService ContentViewsSearchRpmEnvironmentsList", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var serviceContentViewHref string

		resp, httpRes, err := apiClient.ContentViewsRpmEnvironmentsAPI.ContentViewsSearchRpmEnvironmentsList(context.Background(), serviceContentViewHref).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
