/*
Pulp 3 API

Testing RepositoriesPythonBlocklistEntriesAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package zest

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "github.com/content-services/zest/release/v2026"
)

func Test_zest_RepositoriesPythonBlocklistEntriesAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test RepositoriesPythonBlocklistEntriesAPIService RepositoriesPythonPythonBlocklistEntriesCreate", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var pythonPythonRepositoryHref string

		resp, httpRes, err := apiClient.RepositoriesPythonBlocklistEntriesAPI.RepositoriesPythonPythonBlocklistEntriesCreate(context.Background(), pythonPythonRepositoryHref).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test RepositoriesPythonBlocklistEntriesAPIService RepositoriesPythonPythonBlocklistEntriesDelete", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var pythonPythonPythonBlocklistEntryHref string

		httpRes, err := apiClient.RepositoriesPythonBlocklistEntriesAPI.RepositoriesPythonPythonBlocklistEntriesDelete(context.Background(), pythonPythonPythonBlocklistEntryHref).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test RepositoriesPythonBlocklistEntriesAPIService RepositoriesPythonPythonBlocklistEntriesList", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var pythonPythonRepositoryHref string

		resp, httpRes, err := apiClient.RepositoriesPythonBlocklistEntriesAPI.RepositoriesPythonPythonBlocklistEntriesList(context.Background(), pythonPythonRepositoryHref).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test RepositoriesPythonBlocklistEntriesAPIService RepositoriesPythonPythonBlocklistEntriesRead", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var pythonPythonPythonBlocklistEntryHref string

		resp, httpRes, err := apiClient.RepositoriesPythonBlocklistEntriesAPI.RepositoriesPythonPythonBlocklistEntriesRead(context.Background(), pythonPythonPythonBlocklistEntryHref).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
