/*
Pulp 3 API

Testing ApiPypiSimpleAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package zest

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "github.com/content-services/zest/release/v2025"
)

func Test_zest_ApiPypiSimpleAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test ApiPypiSimpleAPIService ApiPulpPypiSimpleCreate", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var path string
		var pulpDomain string

		resp, httpRes, err := apiClient.ApiPypiSimpleAPI.ApiPulpPypiSimpleCreate(context.Background(), path, pulpDomain).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test ApiPypiSimpleAPIService ApiPulpPypiSimpleRead", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var path string
		var pulpDomain string

		httpRes, err := apiClient.ApiPypiSimpleAPI.ApiPulpPypiSimpleRead(context.Background(), path, pulpDomain).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test ApiPypiSimpleAPIService PypiSimplePackageRead", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var package_ string
		var path string
		var pulpDomain string

		httpRes, err := apiClient.ApiPypiSimpleAPI.PypiSimplePackageRead(context.Background(), package_, path, pulpDomain).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
