/*
Pulp 3 API

Testing ContentGemAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package zest

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "github.com/content-services/zest/release/v2026"
)

func Test_zest_ContentGemAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test ContentGemAPIService ContentGemGemCreate", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var pulpDomain string

		resp, httpRes, err := apiClient.ContentGemAPI.ContentGemGemCreate(context.Background(), pulpDomain).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test ContentGemAPIService ContentGemGemList", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var pulpDomain string

		resp, httpRes, err := apiClient.ContentGemAPI.ContentGemGemList(context.Background(), pulpDomain).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test ContentGemAPIService ContentGemGemRead", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var gemGemContentHref string

		resp, httpRes, err := apiClient.ContentGemAPI.ContentGemGemRead(context.Background(), gemGemContentHref).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test ContentGemAPIService ContentGemGemSetLabel", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var gemGemContentHref string

		resp, httpRes, err := apiClient.ContentGemAPI.ContentGemGemSetLabel(context.Background(), gemGemContentHref).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test ContentGemAPIService ContentGemGemUnsetLabel", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var gemGemContentHref string

		resp, httpRes, err := apiClient.ContentGemAPI.ContentGemGemUnsetLabel(context.Background(), gemGemContentHref).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
