/*
Pulp 3 API

Fetch, Upload, Organize, and Distribute Software Packages

API version: v3
Contact: pulp-list@redhat.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package zest

import (
	"bytes"
	"context"
	"io"
	"net/http"
	"net/url"
	"reflect"
)


// ApiDebugCleanupStaleLocksAPIService ApiDebugCleanupStaleLocksAPI service
type ApiDebugCleanupStaleLocksAPIService service

type ApiDebugCleanupStaleLocksAPIApiPulpDebugCleanupStaleLocksGetRequest struct {
	ctx context.Context
	ApiService *ApiDebugCleanupStaleLocksAPIService
	xTaskDiagnostics *[]string
	fields *[]string
	excludeFields *[]string
}

// List of profilers to use on tasks.
func (r ApiDebugCleanupStaleLocksAPIApiPulpDebugCleanupStaleLocksGetRequest) XTaskDiagnostics(xTaskDiagnostics []string) ApiDebugCleanupStaleLocksAPIApiPulpDebugCleanupStaleLocksGetRequest {
	r.xTaskDiagnostics = &xTaskDiagnostics
	return r
}

// A list of fields to include in the response.
func (r ApiDebugCleanupStaleLocksAPIApiPulpDebugCleanupStaleLocksGetRequest) Fields(fields []string) ApiDebugCleanupStaleLocksAPIApiPulpDebugCleanupStaleLocksGetRequest {
	r.fields = &fields
	return r
}

// A list of fields to exclude from the response.
func (r ApiDebugCleanupStaleLocksAPIApiPulpDebugCleanupStaleLocksGetRequest) ExcludeFields(excludeFields []string) ApiDebugCleanupStaleLocksAPIApiPulpDebugCleanupStaleLocksGetRequest {
	r.excludeFields = &excludeFields
	return r
}

func (r ApiDebugCleanupStaleLocksAPIApiPulpDebugCleanupStaleLocksGetRequest) Execute() (*http.Response, error) {
	return r.ApiService.ApiPulpDebugCleanupStaleLocksGetExecute(r)
}

/*
ApiPulpDebugCleanupStaleLocksGet Method for ApiPulpDebugCleanupStaleLocksGet

Return endpoint documentation.

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @return ApiDebugCleanupStaleLocksAPIApiPulpDebugCleanupStaleLocksGetRequest
*/
func (a *ApiDebugCleanupStaleLocksAPIService) ApiPulpDebugCleanupStaleLocksGet(ctx context.Context) ApiDebugCleanupStaleLocksAPIApiPulpDebugCleanupStaleLocksGetRequest {
	return ApiDebugCleanupStaleLocksAPIApiPulpDebugCleanupStaleLocksGetRequest{
		ApiService: a,
		ctx: ctx,
	}
}

// Execute executes the request
func (a *ApiDebugCleanupStaleLocksAPIService) ApiPulpDebugCleanupStaleLocksGetExecute(r ApiDebugCleanupStaleLocksAPIApiPulpDebugCleanupStaleLocksGetRequest) (*http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodGet
		localVarPostBody     interface{}
		formFiles            []formFile
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "ApiDebugCleanupStaleLocksAPIService.ApiPulpDebugCleanupStaleLocksGet")
	if err != nil {
		return nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/api/pulp/debug/cleanup-stale-locks/"
	localVarPath, _ = url.PathUnescape(localVarPath)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}

	if r.fields != nil {
		t := *r.fields
		if reflect.TypeOf(t).Kind() == reflect.Slice {
			s := reflect.ValueOf(t)
			for i := 0; i < s.Len(); i++ {
                               parameterAddToHeaderOrQuery(localVarQueryParams, "fields", s.Index(i).Interface(), "form", "multi")
			}
		} else {
			parameterAddToHeaderOrQuery(localVarQueryParams, "fields", t, "form", "multi")
		}
	}
	if r.excludeFields != nil {
		t := *r.excludeFields
		if reflect.TypeOf(t).Kind() == reflect.Slice {
			s := reflect.ValueOf(t)
			for i := 0; i < s.Len(); i++ {
                               parameterAddToHeaderOrQuery(localVarQueryParams, "exclude_fields", s.Index(i).Interface(), "form", "multi")
			}
		} else {
			parameterAddToHeaderOrQuery(localVarQueryParams, "exclude_fields", t, "form", "multi")
		}
	}
	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	if r.xTaskDiagnostics != nil {
		parameterAddToHeaderOrQuery(localVarHeaderParams, "X-Task-Diagnostics", r.xTaskDiagnostics, "simple", "csv")
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		return localVarHTTPResponse, newErr
	}

	return localVarHTTPResponse, nil
}

type ApiDebugCleanupStaleLocksAPIApiPulpDebugCleanupStaleLocksPostRequest struct {
	ctx context.Context
	ApiService *ApiDebugCleanupStaleLocksAPIService
	xTaskDiagnostics *[]string
}

// List of profilers to use on tasks.
func (r ApiDebugCleanupStaleLocksAPIApiPulpDebugCleanupStaleLocksPostRequest) XTaskDiagnostics(xTaskDiagnostics []string) ApiDebugCleanupStaleLocksAPIApiPulpDebugCleanupStaleLocksPostRequest {
	r.xTaskDiagnostics = &xTaskDiagnostics
	return r
}

func (r ApiDebugCleanupStaleLocksAPIApiPulpDebugCleanupStaleLocksPostRequest) Execute() (*AsyncOperationResponse, *http.Response, error) {
	return r.ApiService.ApiPulpDebugCleanupStaleLocksPostExecute(r)
}

/*
ApiPulpDebugCleanupStaleLocksPost Dispatch stale lock cleanup

Dispatch a background task that scans Redis for orphaned locks and removes them.

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @return ApiDebugCleanupStaleLocksAPIApiPulpDebugCleanupStaleLocksPostRequest
*/
func (a *ApiDebugCleanupStaleLocksAPIService) ApiPulpDebugCleanupStaleLocksPost(ctx context.Context) ApiDebugCleanupStaleLocksAPIApiPulpDebugCleanupStaleLocksPostRequest {
	return ApiDebugCleanupStaleLocksAPIApiPulpDebugCleanupStaleLocksPostRequest{
		ApiService: a,
		ctx: ctx,
	}
}

// Execute executes the request
//  @return AsyncOperationResponse
func (a *ApiDebugCleanupStaleLocksAPIService) ApiPulpDebugCleanupStaleLocksPostExecute(r ApiDebugCleanupStaleLocksAPIApiPulpDebugCleanupStaleLocksPostRequest) (*AsyncOperationResponse, *http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodPost
		localVarPostBody     interface{}
		formFiles            []formFile
		localVarReturnValue  *AsyncOperationResponse
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "ApiDebugCleanupStaleLocksAPIService.ApiPulpDebugCleanupStaleLocksPost")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/api/pulp/debug/cleanup-stale-locks/"
	localVarPath, _ = url.PathUnescape(localVarPath)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	if r.xTaskDiagnostics != nil {
		parameterAddToHeaderOrQuery(localVarHeaderParams, "X-Task-Diagnostics", r.xTaskDiagnostics, "simple", "csv")
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}
