/*
Pulp 3 API

Fetch, Upload, Organize, and Distribute Software Packages

API version: v3
Contact: pulp-list@redhat.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package zest

import (
	"bytes"
	"context"
	"io"
	"net/http"
	"net/url"
	"strings"
	"reflect"
)


// PypiYankMonitorAPIService PypiYankMonitorAPI service
type PypiYankMonitorAPIService service

type PypiYankMonitorAPIPypiYankMonitorAddRoleRequest struct {
	ctx context.Context
	ApiService *PypiYankMonitorAPIService
	servicePyPIYankMonitorHref string
	nestedRole *NestedRole
	xTaskDiagnostics *[]string
}

func (r PypiYankMonitorAPIPypiYankMonitorAddRoleRequest) NestedRole(nestedRole NestedRole) PypiYankMonitorAPIPypiYankMonitorAddRoleRequest {
	r.nestedRole = &nestedRole
	return r
}

// List of profilers to use on tasks.
func (r PypiYankMonitorAPIPypiYankMonitorAddRoleRequest) XTaskDiagnostics(xTaskDiagnostics []string) PypiYankMonitorAPIPypiYankMonitorAddRoleRequest {
	r.xTaskDiagnostics = &xTaskDiagnostics
	return r
}

func (r PypiYankMonitorAPIPypiYankMonitorAddRoleRequest) Execute() (*NestedRoleResponse, *http.Response, error) {
	return r.ApiService.PypiYankMonitorAddRoleExecute(r)
}

/*
PypiYankMonitorAddRole Add a role

Add a role for this object to users/groups.

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @param servicePyPIYankMonitorHref
 @return PypiYankMonitorAPIPypiYankMonitorAddRoleRequest
*/
func (a *PypiYankMonitorAPIService) PypiYankMonitorAddRole(ctx context.Context, servicePyPIYankMonitorHref string) PypiYankMonitorAPIPypiYankMonitorAddRoleRequest {
	return PypiYankMonitorAPIPypiYankMonitorAddRoleRequest{
		ApiService: a,
		ctx: ctx,
		servicePyPIYankMonitorHref: servicePyPIYankMonitorHref,
	}
}

// Execute executes the request
//  @return NestedRoleResponse
func (a *PypiYankMonitorAPIService) PypiYankMonitorAddRoleExecute(r PypiYankMonitorAPIPypiYankMonitorAddRoleRequest) (*NestedRoleResponse, *http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodPost
		localVarPostBody     interface{}
		formFiles            []formFile
		localVarReturnValue  *NestedRoleResponse
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "PypiYankMonitorAPIService.PypiYankMonitorAddRole")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/{service_py_p_i_yank_monitor_href}add_role/"
	localVarPath = strings.Replace(localVarPath, "{"+"service_py_p_i_yank_monitor_href"+"}", url.PathEscape(parameterValueToString(r.servicePyPIYankMonitorHref, "servicePyPIYankMonitorHref")), -1)
	localVarPath, _ = url.PathUnescape(localVarPath)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}
	if r.nestedRole == nil {
		return localVarReturnValue, nil, reportError("nestedRole is required and must be specified")
	}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{"application/json", "application/x-www-form-urlencoded", "multipart/form-data"}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	if r.xTaskDiagnostics != nil {
		parameterAddToHeaderOrQuery(localVarHeaderParams, "X-Task-Diagnostics", r.xTaskDiagnostics, "simple", "csv")
	}
	// body params
	localVarPostBody = r.nestedRole
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}

type PypiYankMonitorAPIPypiYankMonitorCheckRequest struct {
	ctx context.Context
	ApiService *PypiYankMonitorAPIService
	servicePyPIYankMonitorHref string
	xTaskDiagnostics *[]string
}

// List of profilers to use on tasks.
func (r PypiYankMonitorAPIPypiYankMonitorCheckRequest) XTaskDiagnostics(xTaskDiagnostics []string) PypiYankMonitorAPIPypiYankMonitorCheckRequest {
	r.xTaskDiagnostics = &xTaskDiagnostics
	return r
}

func (r PypiYankMonitorAPIPypiYankMonitorCheckRequest) Execute() (*AsyncOperationResponse, *http.Response, error) {
	return r.ApiService.PypiYankMonitorCheckExecute(r)
}

/*
PypiYankMonitorCheck Method for PypiYankMonitorCheck

A customized named ModelViewSet that knows how to register itself with the Pulp API router.This viewset is discoverable by its name."Normal" Django Models and Master/Detail models are supported by the `register_with` method.Attributes:    lookup_field (str): The name of the field by which an object should be looked up, in        addition to any parent lookups if this ViewSet is nested. Defaults to 'pk'    endpoint_name (str): The name of the final path segment that should identify the ViewSet's        collection endpoint.    nest_prefix (str): Optional prefix under which this ViewSet should be nested. This must        correspond to the "parent_prefix" of a router with rest_framework_nested.NestedMixin.        None indicates this ViewSet should not be nested.    parent_lookup_kwargs (dict): Optional mapping of key names that would appear in self.kwargs        to django model filter expressions that can be used with the corresponding value from        self.kwargs, used only by a nested ViewSet to filter based on the parent object's        identity.    schema (DefaultSchema): The schema class to use by default in a viewset.

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @param servicePyPIYankMonitorHref
 @return PypiYankMonitorAPIPypiYankMonitorCheckRequest
*/
func (a *PypiYankMonitorAPIService) PypiYankMonitorCheck(ctx context.Context, servicePyPIYankMonitorHref string) PypiYankMonitorAPIPypiYankMonitorCheckRequest {
	return PypiYankMonitorAPIPypiYankMonitorCheckRequest{
		ApiService: a,
		ctx: ctx,
		servicePyPIYankMonitorHref: servicePyPIYankMonitorHref,
	}
}

// Execute executes the request
//  @return AsyncOperationResponse
func (a *PypiYankMonitorAPIService) PypiYankMonitorCheckExecute(r PypiYankMonitorAPIPypiYankMonitorCheckRequest) (*AsyncOperationResponse, *http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodPost
		localVarPostBody     interface{}
		formFiles            []formFile
		localVarReturnValue  *AsyncOperationResponse
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "PypiYankMonitorAPIService.PypiYankMonitorCheck")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/{service_py_p_i_yank_monitor_href}check/"
	localVarPath = strings.Replace(localVarPath, "{"+"service_py_p_i_yank_monitor_href"+"}", url.PathEscape(parameterValueToString(r.servicePyPIYankMonitorHref, "servicePyPIYankMonitorHref")), -1)
	localVarPath, _ = url.PathUnescape(localVarPath)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	if r.xTaskDiagnostics != nil {
		parameterAddToHeaderOrQuery(localVarHeaderParams, "X-Task-Diagnostics", r.xTaskDiagnostics, "simple", "csv")
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}

type PypiYankMonitorAPIPypiYankMonitorCreateRequest struct {
	ctx context.Context
	ApiService *PypiYankMonitorAPIService
	pulpDomain string
	servicePyPIYankMonitor *ServicePyPIYankMonitor
	xTaskDiagnostics *[]string
}

func (r PypiYankMonitorAPIPypiYankMonitorCreateRequest) ServicePyPIYankMonitor(servicePyPIYankMonitor ServicePyPIYankMonitor) PypiYankMonitorAPIPypiYankMonitorCreateRequest {
	r.servicePyPIYankMonitor = &servicePyPIYankMonitor
	return r
}

// List of profilers to use on tasks.
func (r PypiYankMonitorAPIPypiYankMonitorCreateRequest) XTaskDiagnostics(xTaskDiagnostics []string) PypiYankMonitorAPIPypiYankMonitorCreateRequest {
	r.xTaskDiagnostics = &xTaskDiagnostics
	return r
}

func (r PypiYankMonitorAPIPypiYankMonitorCreateRequest) Execute() (*ServicePyPIYankMonitorResponse, *http.Response, error) {
	return r.ApiService.PypiYankMonitorCreateExecute(r)
}

/*
PypiYankMonitorCreate Create a py pi yank monitor

A customized named ModelViewSet that knows how to register itself with the Pulp API router.This viewset is discoverable by its name."Normal" Django Models and Master/Detail models are supported by the `register_with` method.Attributes:    lookup_field (str): The name of the field by which an object should be looked up, in        addition to any parent lookups if this ViewSet is nested. Defaults to 'pk'    endpoint_name (str): The name of the final path segment that should identify the ViewSet's        collection endpoint.    nest_prefix (str): Optional prefix under which this ViewSet should be nested. This must        correspond to the "parent_prefix" of a router with rest_framework_nested.NestedMixin.        None indicates this ViewSet should not be nested.    parent_lookup_kwargs (dict): Optional mapping of key names that would appear in self.kwargs        to django model filter expressions that can be used with the corresponding value from        self.kwargs, used only by a nested ViewSet to filter based on the parent object's        identity.    schema (DefaultSchema): The schema class to use by default in a viewset.

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @param pulpDomain
 @return PypiYankMonitorAPIPypiYankMonitorCreateRequest
*/
func (a *PypiYankMonitorAPIService) PypiYankMonitorCreate(ctx context.Context, pulpDomain string) PypiYankMonitorAPIPypiYankMonitorCreateRequest {
	return PypiYankMonitorAPIPypiYankMonitorCreateRequest{
		ApiService: a,
		ctx: ctx,
		pulpDomain: pulpDomain,
	}
}

// Execute executes the request
//  @return ServicePyPIYankMonitorResponse
func (a *PypiYankMonitorAPIService) PypiYankMonitorCreateExecute(r PypiYankMonitorAPIPypiYankMonitorCreateRequest) (*ServicePyPIYankMonitorResponse, *http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodPost
		localVarPostBody     interface{}
		formFiles            []formFile
		localVarReturnValue  *ServicePyPIYankMonitorResponse
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "PypiYankMonitorAPIService.PypiYankMonitorCreate")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/api/pulp/{pulp_domain}/api/v3/pypi_yank_monitor/"
	localVarPath = strings.Replace(localVarPath, "{"+"pulp_domain"+"}", url.PathEscape(parameterValueToString(r.pulpDomain, "pulpDomain")), -1)
	localVarPath, _ = url.PathUnescape(localVarPath)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}
	if r.servicePyPIYankMonitor == nil {
		return localVarReturnValue, nil, reportError("servicePyPIYankMonitor is required and must be specified")
	}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{"application/json", "application/x-www-form-urlencoded", "multipart/form-data"}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	if r.xTaskDiagnostics != nil {
		parameterAddToHeaderOrQuery(localVarHeaderParams, "X-Task-Diagnostics", r.xTaskDiagnostics, "simple", "csv")
	}
	// body params
	localVarPostBody = r.servicePyPIYankMonitor
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}

type PypiYankMonitorAPIPypiYankMonitorDeleteRequest struct {
	ctx context.Context
	ApiService *PypiYankMonitorAPIService
	servicePyPIYankMonitorHref string
	xTaskDiagnostics *[]string
}

// List of profilers to use on tasks.
func (r PypiYankMonitorAPIPypiYankMonitorDeleteRequest) XTaskDiagnostics(xTaskDiagnostics []string) PypiYankMonitorAPIPypiYankMonitorDeleteRequest {
	r.xTaskDiagnostics = &xTaskDiagnostics
	return r
}

func (r PypiYankMonitorAPIPypiYankMonitorDeleteRequest) Execute() (*http.Response, error) {
	return r.ApiService.PypiYankMonitorDeleteExecute(r)
}

/*
PypiYankMonitorDelete Delete a py pi yank monitor

A customized named ModelViewSet that knows how to register itself with the Pulp API router.This viewset is discoverable by its name."Normal" Django Models and Master/Detail models are supported by the `register_with` method.Attributes:    lookup_field (str): The name of the field by which an object should be looked up, in        addition to any parent lookups if this ViewSet is nested. Defaults to 'pk'    endpoint_name (str): The name of the final path segment that should identify the ViewSet's        collection endpoint.    nest_prefix (str): Optional prefix under which this ViewSet should be nested. This must        correspond to the "parent_prefix" of a router with rest_framework_nested.NestedMixin.        None indicates this ViewSet should not be nested.    parent_lookup_kwargs (dict): Optional mapping of key names that would appear in self.kwargs        to django model filter expressions that can be used with the corresponding value from        self.kwargs, used only by a nested ViewSet to filter based on the parent object's        identity.    schema (DefaultSchema): The schema class to use by default in a viewset.

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @param servicePyPIYankMonitorHref
 @return PypiYankMonitorAPIPypiYankMonitorDeleteRequest
*/
func (a *PypiYankMonitorAPIService) PypiYankMonitorDelete(ctx context.Context, servicePyPIYankMonitorHref string) PypiYankMonitorAPIPypiYankMonitorDeleteRequest {
	return PypiYankMonitorAPIPypiYankMonitorDeleteRequest{
		ApiService: a,
		ctx: ctx,
		servicePyPIYankMonitorHref: servicePyPIYankMonitorHref,
	}
}

// Execute executes the request
func (a *PypiYankMonitorAPIService) PypiYankMonitorDeleteExecute(r PypiYankMonitorAPIPypiYankMonitorDeleteRequest) (*http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodDelete
		localVarPostBody     interface{}
		formFiles            []formFile
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "PypiYankMonitorAPIService.PypiYankMonitorDelete")
	if err != nil {
		return nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/{service_py_p_i_yank_monitor_href}"
	localVarPath = strings.Replace(localVarPath, "{"+"service_py_p_i_yank_monitor_href"+"}", url.PathEscape(parameterValueToString(r.servicePyPIYankMonitorHref, "servicePyPIYankMonitorHref")), -1)
	localVarPath, _ = url.PathUnescape(localVarPath)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	if r.xTaskDiagnostics != nil {
		parameterAddToHeaderOrQuery(localVarHeaderParams, "X-Task-Diagnostics", r.xTaskDiagnostics, "simple", "csv")
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		return localVarHTTPResponse, newErr
	}

	return localVarHTTPResponse, nil
}

type PypiYankMonitorAPIPypiYankMonitorListRequest struct {
	ctx context.Context
	ApiService *PypiYankMonitorAPIService
	pulpDomain string
	xTaskDiagnostics *[]string
	limit *int32
	name *string
	nameContains *string
	nameIcontains *string
	nameIexact *string
	nameIn *[]string
	nameIregex *string
	nameIstartswith *string
	nameRegex *string
	nameStartswith *string
	offset *int32
	ordering *[]string
	prnIn *[]string
	pulpHrefIn *[]string
	pulpIdIn *[]string
	pulpLabelSelect *string
	q *string
	repository *string
	fields *[]string
	excludeFields *[]string
}

// List of profilers to use on tasks.
func (r PypiYankMonitorAPIPypiYankMonitorListRequest) XTaskDiagnostics(xTaskDiagnostics []string) PypiYankMonitorAPIPypiYankMonitorListRequest {
	r.xTaskDiagnostics = &xTaskDiagnostics
	return r
}

// Number of results to return per page.
func (r PypiYankMonitorAPIPypiYankMonitorListRequest) Limit(limit int32) PypiYankMonitorAPIPypiYankMonitorListRequest {
	r.limit = &limit
	return r
}

// Filter results where name matches value
func (r PypiYankMonitorAPIPypiYankMonitorListRequest) Name(name string) PypiYankMonitorAPIPypiYankMonitorListRequest {
	r.name = &name
	return r
}

// Filter results where name contains value
func (r PypiYankMonitorAPIPypiYankMonitorListRequest) NameContains(nameContains string) PypiYankMonitorAPIPypiYankMonitorListRequest {
	r.nameContains = &nameContains
	return r
}

// Filter results where name contains value
func (r PypiYankMonitorAPIPypiYankMonitorListRequest) NameIcontains(nameIcontains string) PypiYankMonitorAPIPypiYankMonitorListRequest {
	r.nameIcontains = &nameIcontains
	return r
}

// Filter results where name matches value
func (r PypiYankMonitorAPIPypiYankMonitorListRequest) NameIexact(nameIexact string) PypiYankMonitorAPIPypiYankMonitorListRequest {
	r.nameIexact = &nameIexact
	return r
}

// Filter results where name is in a comma-separated list of values
func (r PypiYankMonitorAPIPypiYankMonitorListRequest) NameIn(nameIn []string) PypiYankMonitorAPIPypiYankMonitorListRequest {
	r.nameIn = &nameIn
	return r
}

// Filter results where name matches regex value
func (r PypiYankMonitorAPIPypiYankMonitorListRequest) NameIregex(nameIregex string) PypiYankMonitorAPIPypiYankMonitorListRequest {
	r.nameIregex = &nameIregex
	return r
}

// Filter results where name starts with value
func (r PypiYankMonitorAPIPypiYankMonitorListRequest) NameIstartswith(nameIstartswith string) PypiYankMonitorAPIPypiYankMonitorListRequest {
	r.nameIstartswith = &nameIstartswith
	return r
}

// Filter results where name matches regex value
func (r PypiYankMonitorAPIPypiYankMonitorListRequest) NameRegex(nameRegex string) PypiYankMonitorAPIPypiYankMonitorListRequest {
	r.nameRegex = &nameRegex
	return r
}

// Filter results where name starts with value
func (r PypiYankMonitorAPIPypiYankMonitorListRequest) NameStartswith(nameStartswith string) PypiYankMonitorAPIPypiYankMonitorListRequest {
	r.nameStartswith = &nameStartswith
	return r
}

// The initial index from which to return the results.
func (r PypiYankMonitorAPIPypiYankMonitorListRequest) Offset(offset int32) PypiYankMonitorAPIPypiYankMonitorListRequest {
	r.offset = &offset
	return r
}

// Ordering* &#x60;pulp_id&#x60; - Pulp id* &#x60;-pulp_id&#x60; - Pulp id (descending)* &#x60;pulp_created&#x60; - Pulp created* &#x60;-pulp_created&#x60; - Pulp created (descending)* &#x60;pulp_last_updated&#x60; - Pulp last updated* &#x60;-pulp_last_updated&#x60; - Pulp last updated (descending)* &#x60;name&#x60; - Name* &#x60;-name&#x60; - Name (descending)* &#x60;description&#x60; - Description* &#x60;-description&#x60; - Description (descending)* &#x60;pulp_labels&#x60; - Pulp labels* &#x60;-pulp_labels&#x60; - Pulp labels (descending)* &#x60;last_checked&#x60; - Last checked* &#x60;-last_checked&#x60; - Last checked (descending)* &#x60;pk&#x60; - Pk* &#x60;-pk&#x60; - Pk (descending)
func (r PypiYankMonitorAPIPypiYankMonitorListRequest) Ordering(ordering []string) PypiYankMonitorAPIPypiYankMonitorListRequest {
	r.ordering = &ordering
	return r
}

// Multiple values may be separated by commas.
func (r PypiYankMonitorAPIPypiYankMonitorListRequest) PrnIn(prnIn []string) PypiYankMonitorAPIPypiYankMonitorListRequest {
	r.prnIn = &prnIn
	return r
}

// Multiple values may be separated by commas.
func (r PypiYankMonitorAPIPypiYankMonitorListRequest) PulpHrefIn(pulpHrefIn []string) PypiYankMonitorAPIPypiYankMonitorListRequest {
	r.pulpHrefIn = &pulpHrefIn
	return r
}

// Multiple values may be separated by commas.
func (r PypiYankMonitorAPIPypiYankMonitorListRequest) PulpIdIn(pulpIdIn []string) PypiYankMonitorAPIPypiYankMonitorListRequest {
	r.pulpIdIn = &pulpIdIn
	return r
}

// Filter labels by search string
func (r PypiYankMonitorAPIPypiYankMonitorListRequest) PulpLabelSelect(pulpLabelSelect string) PypiYankMonitorAPIPypiYankMonitorListRequest {
	r.pulpLabelSelect = &pulpLabelSelect
	return r
}

// Filter results by using NOT, AND and OR operations on other filters
func (r PypiYankMonitorAPIPypiYankMonitorListRequest) Q(q string) PypiYankMonitorAPIPypiYankMonitorListRequest {
	r.q = &q
	return r
}

func (r PypiYankMonitorAPIPypiYankMonitorListRequest) Repository(repository string) PypiYankMonitorAPIPypiYankMonitorListRequest {
	r.repository = &repository
	return r
}

// A list of fields to include in the response.
func (r PypiYankMonitorAPIPypiYankMonitorListRequest) Fields(fields []string) PypiYankMonitorAPIPypiYankMonitorListRequest {
	r.fields = &fields
	return r
}

// A list of fields to exclude from the response.
func (r PypiYankMonitorAPIPypiYankMonitorListRequest) ExcludeFields(excludeFields []string) PypiYankMonitorAPIPypiYankMonitorListRequest {
	r.excludeFields = &excludeFields
	return r
}

func (r PypiYankMonitorAPIPypiYankMonitorListRequest) Execute() (*PaginatedservicePyPIYankMonitorResponseList, *http.Response, error) {
	return r.ApiService.PypiYankMonitorListExecute(r)
}

/*
PypiYankMonitorList List py pi yank monitors

A customized named ModelViewSet that knows how to register itself with the Pulp API router.This viewset is discoverable by its name."Normal" Django Models and Master/Detail models are supported by the `register_with` method.Attributes:    lookup_field (str): The name of the field by which an object should be looked up, in        addition to any parent lookups if this ViewSet is nested. Defaults to 'pk'    endpoint_name (str): The name of the final path segment that should identify the ViewSet's        collection endpoint.    nest_prefix (str): Optional prefix under which this ViewSet should be nested. This must        correspond to the "parent_prefix" of a router with rest_framework_nested.NestedMixin.        None indicates this ViewSet should not be nested.    parent_lookup_kwargs (dict): Optional mapping of key names that would appear in self.kwargs        to django model filter expressions that can be used with the corresponding value from        self.kwargs, used only by a nested ViewSet to filter based on the parent object's        identity.    schema (DefaultSchema): The schema class to use by default in a viewset.

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @param pulpDomain
 @return PypiYankMonitorAPIPypiYankMonitorListRequest
*/
func (a *PypiYankMonitorAPIService) PypiYankMonitorList(ctx context.Context, pulpDomain string) PypiYankMonitorAPIPypiYankMonitorListRequest {
	return PypiYankMonitorAPIPypiYankMonitorListRequest{
		ApiService: a,
		ctx: ctx,
		pulpDomain: pulpDomain,
	}
}

// Execute executes the request
//  @return PaginatedservicePyPIYankMonitorResponseList
func (a *PypiYankMonitorAPIService) PypiYankMonitorListExecute(r PypiYankMonitorAPIPypiYankMonitorListRequest) (*PaginatedservicePyPIYankMonitorResponseList, *http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodGet
		localVarPostBody     interface{}
		formFiles            []formFile
		localVarReturnValue  *PaginatedservicePyPIYankMonitorResponseList
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "PypiYankMonitorAPIService.PypiYankMonitorList")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/api/pulp/{pulp_domain}/api/v3/pypi_yank_monitor/"
	localVarPath = strings.Replace(localVarPath, "{"+"pulp_domain"+"}", url.PathEscape(parameterValueToString(r.pulpDomain, "pulpDomain")), -1)
	localVarPath, _ = url.PathUnescape(localVarPath)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}

	if r.limit != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "limit", r.limit, "form", "")
	}
	if r.name != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "name", r.name, "form", "")
	}
	if r.nameContains != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "name__contains", r.nameContains, "form", "")
	}
	if r.nameIcontains != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "name__icontains", r.nameIcontains, "form", "")
	}
	if r.nameIexact != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "name__iexact", r.nameIexact, "form", "")
	}
	if r.nameIn != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "name__in", r.nameIn, "form", "csv")
	}
	if r.nameIregex != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "name__iregex", r.nameIregex, "form", "")
	}
	if r.nameIstartswith != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "name__istartswith", r.nameIstartswith, "form", "")
	}
	if r.nameRegex != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "name__regex", r.nameRegex, "form", "")
	}
	if r.nameStartswith != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "name__startswith", r.nameStartswith, "form", "")
	}
	if r.offset != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "offset", r.offset, "form", "")
	}
	if r.ordering != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "ordering", r.ordering, "form", "csv")
	}
	if r.prnIn != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "prn__in", r.prnIn, "form", "csv")
	}
	if r.pulpHrefIn != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "pulp_href__in", r.pulpHrefIn, "form", "csv")
	}
	if r.pulpIdIn != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "pulp_id__in", r.pulpIdIn, "form", "csv")
	}
	if r.pulpLabelSelect != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "pulp_label_select", r.pulpLabelSelect, "form", "")
	}
	if r.q != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "q", r.q, "form", "")
	}
	if r.repository != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "repository", r.repository, "form", "")
	}
	if r.fields != nil {
		t := *r.fields
		if reflect.TypeOf(t).Kind() == reflect.Slice {
			s := reflect.ValueOf(t)
			for i := 0; i < s.Len(); i++ {
                               parameterAddToHeaderOrQuery(localVarQueryParams, "fields", s.Index(i).Interface(), "form", "multi")
			}
		} else {
			parameterAddToHeaderOrQuery(localVarQueryParams, "fields", t, "form", "multi")
		}
	}
	if r.excludeFields != nil {
		t := *r.excludeFields
		if reflect.TypeOf(t).Kind() == reflect.Slice {
			s := reflect.ValueOf(t)
			for i := 0; i < s.Len(); i++ {
                               parameterAddToHeaderOrQuery(localVarQueryParams, "exclude_fields", s.Index(i).Interface(), "form", "multi")
			}
		} else {
			parameterAddToHeaderOrQuery(localVarQueryParams, "exclude_fields", t, "form", "multi")
		}
	}
	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	if r.xTaskDiagnostics != nil {
		parameterAddToHeaderOrQuery(localVarHeaderParams, "X-Task-Diagnostics", r.xTaskDiagnostics, "simple", "csv")
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}

type PypiYankMonitorAPIPypiYankMonitorListRolesRequest struct {
	ctx context.Context
	ApiService *PypiYankMonitorAPIService
	servicePyPIYankMonitorHref string
	xTaskDiagnostics *[]string
	fields *[]string
	excludeFields *[]string
}

// List of profilers to use on tasks.
func (r PypiYankMonitorAPIPypiYankMonitorListRolesRequest) XTaskDiagnostics(xTaskDiagnostics []string) PypiYankMonitorAPIPypiYankMonitorListRolesRequest {
	r.xTaskDiagnostics = &xTaskDiagnostics
	return r
}

// A list of fields to include in the response.
func (r PypiYankMonitorAPIPypiYankMonitorListRolesRequest) Fields(fields []string) PypiYankMonitorAPIPypiYankMonitorListRolesRequest {
	r.fields = &fields
	return r
}

// A list of fields to exclude from the response.
func (r PypiYankMonitorAPIPypiYankMonitorListRolesRequest) ExcludeFields(excludeFields []string) PypiYankMonitorAPIPypiYankMonitorListRolesRequest {
	r.excludeFields = &excludeFields
	return r
}

func (r PypiYankMonitorAPIPypiYankMonitorListRolesRequest) Execute() (*ObjectRolesResponse, *http.Response, error) {
	return r.ApiService.PypiYankMonitorListRolesExecute(r)
}

/*
PypiYankMonitorListRoles List roles

List roles assigned to this object.

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @param servicePyPIYankMonitorHref
 @return PypiYankMonitorAPIPypiYankMonitorListRolesRequest
*/
func (a *PypiYankMonitorAPIService) PypiYankMonitorListRoles(ctx context.Context, servicePyPIYankMonitorHref string) PypiYankMonitorAPIPypiYankMonitorListRolesRequest {
	return PypiYankMonitorAPIPypiYankMonitorListRolesRequest{
		ApiService: a,
		ctx: ctx,
		servicePyPIYankMonitorHref: servicePyPIYankMonitorHref,
	}
}

// Execute executes the request
//  @return ObjectRolesResponse
func (a *PypiYankMonitorAPIService) PypiYankMonitorListRolesExecute(r PypiYankMonitorAPIPypiYankMonitorListRolesRequest) (*ObjectRolesResponse, *http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodGet
		localVarPostBody     interface{}
		formFiles            []formFile
		localVarReturnValue  *ObjectRolesResponse
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "PypiYankMonitorAPIService.PypiYankMonitorListRoles")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/{service_py_p_i_yank_monitor_href}list_roles/"
	localVarPath = strings.Replace(localVarPath, "{"+"service_py_p_i_yank_monitor_href"+"}", url.PathEscape(parameterValueToString(r.servicePyPIYankMonitorHref, "servicePyPIYankMonitorHref")), -1)
	localVarPath, _ = url.PathUnescape(localVarPath)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}

	if r.fields != nil {
		t := *r.fields
		if reflect.TypeOf(t).Kind() == reflect.Slice {
			s := reflect.ValueOf(t)
			for i := 0; i < s.Len(); i++ {
                               parameterAddToHeaderOrQuery(localVarQueryParams, "fields", s.Index(i).Interface(), "form", "multi")
			}
		} else {
			parameterAddToHeaderOrQuery(localVarQueryParams, "fields", t, "form", "multi")
		}
	}
	if r.excludeFields != nil {
		t := *r.excludeFields
		if reflect.TypeOf(t).Kind() == reflect.Slice {
			s := reflect.ValueOf(t)
			for i := 0; i < s.Len(); i++ {
                               parameterAddToHeaderOrQuery(localVarQueryParams, "exclude_fields", s.Index(i).Interface(), "form", "multi")
			}
		} else {
			parameterAddToHeaderOrQuery(localVarQueryParams, "exclude_fields", t, "form", "multi")
		}
	}
	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	if r.xTaskDiagnostics != nil {
		parameterAddToHeaderOrQuery(localVarHeaderParams, "X-Task-Diagnostics", r.xTaskDiagnostics, "simple", "csv")
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}

type PypiYankMonitorAPIPypiYankMonitorMyPermissionsRequest struct {
	ctx context.Context
	ApiService *PypiYankMonitorAPIService
	servicePyPIYankMonitorHref string
	xTaskDiagnostics *[]string
	fields *[]string
	excludeFields *[]string
}

// List of profilers to use on tasks.
func (r PypiYankMonitorAPIPypiYankMonitorMyPermissionsRequest) XTaskDiagnostics(xTaskDiagnostics []string) PypiYankMonitorAPIPypiYankMonitorMyPermissionsRequest {
	r.xTaskDiagnostics = &xTaskDiagnostics
	return r
}

// A list of fields to include in the response.
func (r PypiYankMonitorAPIPypiYankMonitorMyPermissionsRequest) Fields(fields []string) PypiYankMonitorAPIPypiYankMonitorMyPermissionsRequest {
	r.fields = &fields
	return r
}

// A list of fields to exclude from the response.
func (r PypiYankMonitorAPIPypiYankMonitorMyPermissionsRequest) ExcludeFields(excludeFields []string) PypiYankMonitorAPIPypiYankMonitorMyPermissionsRequest {
	r.excludeFields = &excludeFields
	return r
}

func (r PypiYankMonitorAPIPypiYankMonitorMyPermissionsRequest) Execute() (*MyPermissionsResponse, *http.Response, error) {
	return r.ApiService.PypiYankMonitorMyPermissionsExecute(r)
}

/*
PypiYankMonitorMyPermissions List user permissions

List permissions available to the current user on this object.

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @param servicePyPIYankMonitorHref
 @return PypiYankMonitorAPIPypiYankMonitorMyPermissionsRequest
*/
func (a *PypiYankMonitorAPIService) PypiYankMonitorMyPermissions(ctx context.Context, servicePyPIYankMonitorHref string) PypiYankMonitorAPIPypiYankMonitorMyPermissionsRequest {
	return PypiYankMonitorAPIPypiYankMonitorMyPermissionsRequest{
		ApiService: a,
		ctx: ctx,
		servicePyPIYankMonitorHref: servicePyPIYankMonitorHref,
	}
}

// Execute executes the request
//  @return MyPermissionsResponse
func (a *PypiYankMonitorAPIService) PypiYankMonitorMyPermissionsExecute(r PypiYankMonitorAPIPypiYankMonitorMyPermissionsRequest) (*MyPermissionsResponse, *http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodGet
		localVarPostBody     interface{}
		formFiles            []formFile
		localVarReturnValue  *MyPermissionsResponse
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "PypiYankMonitorAPIService.PypiYankMonitorMyPermissions")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/{service_py_p_i_yank_monitor_href}my_permissions/"
	localVarPath = strings.Replace(localVarPath, "{"+"service_py_p_i_yank_monitor_href"+"}", url.PathEscape(parameterValueToString(r.servicePyPIYankMonitorHref, "servicePyPIYankMonitorHref")), -1)
	localVarPath, _ = url.PathUnescape(localVarPath)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}

	if r.fields != nil {
		t := *r.fields
		if reflect.TypeOf(t).Kind() == reflect.Slice {
			s := reflect.ValueOf(t)
			for i := 0; i < s.Len(); i++ {
                               parameterAddToHeaderOrQuery(localVarQueryParams, "fields", s.Index(i).Interface(), "form", "multi")
			}
		} else {
			parameterAddToHeaderOrQuery(localVarQueryParams, "fields", t, "form", "multi")
		}
	}
	if r.excludeFields != nil {
		t := *r.excludeFields
		if reflect.TypeOf(t).Kind() == reflect.Slice {
			s := reflect.ValueOf(t)
			for i := 0; i < s.Len(); i++ {
                               parameterAddToHeaderOrQuery(localVarQueryParams, "exclude_fields", s.Index(i).Interface(), "form", "multi")
			}
		} else {
			parameterAddToHeaderOrQuery(localVarQueryParams, "exclude_fields", t, "form", "multi")
		}
	}
	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	if r.xTaskDiagnostics != nil {
		parameterAddToHeaderOrQuery(localVarHeaderParams, "X-Task-Diagnostics", r.xTaskDiagnostics, "simple", "csv")
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}

type PypiYankMonitorAPIPypiYankMonitorReadRequest struct {
	ctx context.Context
	ApiService *PypiYankMonitorAPIService
	servicePyPIYankMonitorHref string
	xTaskDiagnostics *[]string
	fields *[]string
	excludeFields *[]string
}

// List of profilers to use on tasks.
func (r PypiYankMonitorAPIPypiYankMonitorReadRequest) XTaskDiagnostics(xTaskDiagnostics []string) PypiYankMonitorAPIPypiYankMonitorReadRequest {
	r.xTaskDiagnostics = &xTaskDiagnostics
	return r
}

// A list of fields to include in the response.
func (r PypiYankMonitorAPIPypiYankMonitorReadRequest) Fields(fields []string) PypiYankMonitorAPIPypiYankMonitorReadRequest {
	r.fields = &fields
	return r
}

// A list of fields to exclude from the response.
func (r PypiYankMonitorAPIPypiYankMonitorReadRequest) ExcludeFields(excludeFields []string) PypiYankMonitorAPIPypiYankMonitorReadRequest {
	r.excludeFields = &excludeFields
	return r
}

func (r PypiYankMonitorAPIPypiYankMonitorReadRequest) Execute() (*ServicePyPIYankMonitorResponse, *http.Response, error) {
	return r.ApiService.PypiYankMonitorReadExecute(r)
}

/*
PypiYankMonitorRead Inspect a py pi yank monitor

A customized named ModelViewSet that knows how to register itself with the Pulp API router.This viewset is discoverable by its name."Normal" Django Models and Master/Detail models are supported by the `register_with` method.Attributes:    lookup_field (str): The name of the field by which an object should be looked up, in        addition to any parent lookups if this ViewSet is nested. Defaults to 'pk'    endpoint_name (str): The name of the final path segment that should identify the ViewSet's        collection endpoint.    nest_prefix (str): Optional prefix under which this ViewSet should be nested. This must        correspond to the "parent_prefix" of a router with rest_framework_nested.NestedMixin.        None indicates this ViewSet should not be nested.    parent_lookup_kwargs (dict): Optional mapping of key names that would appear in self.kwargs        to django model filter expressions that can be used with the corresponding value from        self.kwargs, used only by a nested ViewSet to filter based on the parent object's        identity.    schema (DefaultSchema): The schema class to use by default in a viewset.

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @param servicePyPIYankMonitorHref
 @return PypiYankMonitorAPIPypiYankMonitorReadRequest
*/
func (a *PypiYankMonitorAPIService) PypiYankMonitorRead(ctx context.Context, servicePyPIYankMonitorHref string) PypiYankMonitorAPIPypiYankMonitorReadRequest {
	return PypiYankMonitorAPIPypiYankMonitorReadRequest{
		ApiService: a,
		ctx: ctx,
		servicePyPIYankMonitorHref: servicePyPIYankMonitorHref,
	}
}

// Execute executes the request
//  @return ServicePyPIYankMonitorResponse
func (a *PypiYankMonitorAPIService) PypiYankMonitorReadExecute(r PypiYankMonitorAPIPypiYankMonitorReadRequest) (*ServicePyPIYankMonitorResponse, *http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodGet
		localVarPostBody     interface{}
		formFiles            []formFile
		localVarReturnValue  *ServicePyPIYankMonitorResponse
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "PypiYankMonitorAPIService.PypiYankMonitorRead")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/{service_py_p_i_yank_monitor_href}"
	localVarPath = strings.Replace(localVarPath, "{"+"service_py_p_i_yank_monitor_href"+"}", url.PathEscape(parameterValueToString(r.servicePyPIYankMonitorHref, "servicePyPIYankMonitorHref")), -1)
	localVarPath, _ = url.PathUnescape(localVarPath)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}

	if r.fields != nil {
		t := *r.fields
		if reflect.TypeOf(t).Kind() == reflect.Slice {
			s := reflect.ValueOf(t)
			for i := 0; i < s.Len(); i++ {
                               parameterAddToHeaderOrQuery(localVarQueryParams, "fields", s.Index(i).Interface(), "form", "multi")
			}
		} else {
			parameterAddToHeaderOrQuery(localVarQueryParams, "fields", t, "form", "multi")
		}
	}
	if r.excludeFields != nil {
		t := *r.excludeFields
		if reflect.TypeOf(t).Kind() == reflect.Slice {
			s := reflect.ValueOf(t)
			for i := 0; i < s.Len(); i++ {
                               parameterAddToHeaderOrQuery(localVarQueryParams, "exclude_fields", s.Index(i).Interface(), "form", "multi")
			}
		} else {
			parameterAddToHeaderOrQuery(localVarQueryParams, "exclude_fields", t, "form", "multi")
		}
	}
	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	if r.xTaskDiagnostics != nil {
		parameterAddToHeaderOrQuery(localVarHeaderParams, "X-Task-Diagnostics", r.xTaskDiagnostics, "simple", "csv")
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}

type PypiYankMonitorAPIPypiYankMonitorRemoveRoleRequest struct {
	ctx context.Context
	ApiService *PypiYankMonitorAPIService
	servicePyPIYankMonitorHref string
	nestedRole *NestedRole
	xTaskDiagnostics *[]string
}

func (r PypiYankMonitorAPIPypiYankMonitorRemoveRoleRequest) NestedRole(nestedRole NestedRole) PypiYankMonitorAPIPypiYankMonitorRemoveRoleRequest {
	r.nestedRole = &nestedRole
	return r
}

// List of profilers to use on tasks.
func (r PypiYankMonitorAPIPypiYankMonitorRemoveRoleRequest) XTaskDiagnostics(xTaskDiagnostics []string) PypiYankMonitorAPIPypiYankMonitorRemoveRoleRequest {
	r.xTaskDiagnostics = &xTaskDiagnostics
	return r
}

func (r PypiYankMonitorAPIPypiYankMonitorRemoveRoleRequest) Execute() (*NestedRoleResponse, *http.Response, error) {
	return r.ApiService.PypiYankMonitorRemoveRoleExecute(r)
}

/*
PypiYankMonitorRemoveRole Remove a role

Remove a role for this object from users/groups.

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @param servicePyPIYankMonitorHref
 @return PypiYankMonitorAPIPypiYankMonitorRemoveRoleRequest
*/
func (a *PypiYankMonitorAPIService) PypiYankMonitorRemoveRole(ctx context.Context, servicePyPIYankMonitorHref string) PypiYankMonitorAPIPypiYankMonitorRemoveRoleRequest {
	return PypiYankMonitorAPIPypiYankMonitorRemoveRoleRequest{
		ApiService: a,
		ctx: ctx,
		servicePyPIYankMonitorHref: servicePyPIYankMonitorHref,
	}
}

// Execute executes the request
//  @return NestedRoleResponse
func (a *PypiYankMonitorAPIService) PypiYankMonitorRemoveRoleExecute(r PypiYankMonitorAPIPypiYankMonitorRemoveRoleRequest) (*NestedRoleResponse, *http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodPost
		localVarPostBody     interface{}
		formFiles            []formFile
		localVarReturnValue  *NestedRoleResponse
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "PypiYankMonitorAPIService.PypiYankMonitorRemoveRole")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/{service_py_p_i_yank_monitor_href}remove_role/"
	localVarPath = strings.Replace(localVarPath, "{"+"service_py_p_i_yank_monitor_href"+"}", url.PathEscape(parameterValueToString(r.servicePyPIYankMonitorHref, "servicePyPIYankMonitorHref")), -1)
	localVarPath, _ = url.PathUnescape(localVarPath)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}
	if r.nestedRole == nil {
		return localVarReturnValue, nil, reportError("nestedRole is required and must be specified")
	}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{"application/json", "application/x-www-form-urlencoded", "multipart/form-data"}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	if r.xTaskDiagnostics != nil {
		parameterAddToHeaderOrQuery(localVarHeaderParams, "X-Task-Diagnostics", r.xTaskDiagnostics, "simple", "csv")
	}
	// body params
	localVarPostBody = r.nestedRole
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}

type PypiYankMonitorAPIPypiYankMonitorReportRequest struct {
	ctx context.Context
	ApiService *PypiYankMonitorAPIService
	servicePyPIYankMonitorHref string
	xTaskDiagnostics *[]string
	fields *[]string
	excludeFields *[]string
}

// List of profilers to use on tasks.
func (r PypiYankMonitorAPIPypiYankMonitorReportRequest) XTaskDiagnostics(xTaskDiagnostics []string) PypiYankMonitorAPIPypiYankMonitorReportRequest {
	r.xTaskDiagnostics = &xTaskDiagnostics
	return r
}

// A list of fields to include in the response.
func (r PypiYankMonitorAPIPypiYankMonitorReportRequest) Fields(fields []string) PypiYankMonitorAPIPypiYankMonitorReportRequest {
	r.fields = &fields
	return r
}

// A list of fields to exclude from the response.
func (r PypiYankMonitorAPIPypiYankMonitorReportRequest) ExcludeFields(excludeFields []string) PypiYankMonitorAPIPypiYankMonitorReportRequest {
	r.excludeFields = &excludeFields
	return r
}

func (r PypiYankMonitorAPIPypiYankMonitorReportRequest) Execute() (*ServiceYankedPackageReportResponse, *http.Response, error) {
	return r.ApiService.PypiYankMonitorReportExecute(r)
}

/*
PypiYankMonitorReport Method for PypiYankMonitorReport

A customized named ModelViewSet that knows how to register itself with the Pulp API router.This viewset is discoverable by its name."Normal" Django Models and Master/Detail models are supported by the `register_with` method.Attributes:    lookup_field (str): The name of the field by which an object should be looked up, in        addition to any parent lookups if this ViewSet is nested. Defaults to 'pk'    endpoint_name (str): The name of the final path segment that should identify the ViewSet's        collection endpoint.    nest_prefix (str): Optional prefix under which this ViewSet should be nested. This must        correspond to the "parent_prefix" of a router with rest_framework_nested.NestedMixin.        None indicates this ViewSet should not be nested.    parent_lookup_kwargs (dict): Optional mapping of key names that would appear in self.kwargs        to django model filter expressions that can be used with the corresponding value from        self.kwargs, used only by a nested ViewSet to filter based on the parent object's        identity.    schema (DefaultSchema): The schema class to use by default in a viewset.

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @param servicePyPIYankMonitorHref
 @return PypiYankMonitorAPIPypiYankMonitorReportRequest
*/
func (a *PypiYankMonitorAPIService) PypiYankMonitorReport(ctx context.Context, servicePyPIYankMonitorHref string) PypiYankMonitorAPIPypiYankMonitorReportRequest {
	return PypiYankMonitorAPIPypiYankMonitorReportRequest{
		ApiService: a,
		ctx: ctx,
		servicePyPIYankMonitorHref: servicePyPIYankMonitorHref,
	}
}

// Execute executes the request
//  @return ServiceYankedPackageReportResponse
func (a *PypiYankMonitorAPIService) PypiYankMonitorReportExecute(r PypiYankMonitorAPIPypiYankMonitorReportRequest) (*ServiceYankedPackageReportResponse, *http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodGet
		localVarPostBody     interface{}
		formFiles            []formFile
		localVarReturnValue  *ServiceYankedPackageReportResponse
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "PypiYankMonitorAPIService.PypiYankMonitorReport")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/{service_py_p_i_yank_monitor_href}report/"
	localVarPath = strings.Replace(localVarPath, "{"+"service_py_p_i_yank_monitor_href"+"}", url.PathEscape(parameterValueToString(r.servicePyPIYankMonitorHref, "servicePyPIYankMonitorHref")), -1)
	localVarPath, _ = url.PathUnescape(localVarPath)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}

	if r.fields != nil {
		t := *r.fields
		if reflect.TypeOf(t).Kind() == reflect.Slice {
			s := reflect.ValueOf(t)
			for i := 0; i < s.Len(); i++ {
                               parameterAddToHeaderOrQuery(localVarQueryParams, "fields", s.Index(i).Interface(), "form", "multi")
			}
		} else {
			parameterAddToHeaderOrQuery(localVarQueryParams, "fields", t, "form", "multi")
		}
	}
	if r.excludeFields != nil {
		t := *r.excludeFields
		if reflect.TypeOf(t).Kind() == reflect.Slice {
			s := reflect.ValueOf(t)
			for i := 0; i < s.Len(); i++ {
                               parameterAddToHeaderOrQuery(localVarQueryParams, "exclude_fields", s.Index(i).Interface(), "form", "multi")
			}
		} else {
			parameterAddToHeaderOrQuery(localVarQueryParams, "exclude_fields", t, "form", "multi")
		}
	}
	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	if r.xTaskDiagnostics != nil {
		parameterAddToHeaderOrQuery(localVarHeaderParams, "X-Task-Diagnostics", r.xTaskDiagnostics, "simple", "csv")
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}
