/*
Pulp 3 API

Fetch, Upload, Organize, and Distribute Software Packages

API version: v3
Contact: pulp-list@redhat.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package zest

import (
	"encoding/json"
	"fmt"
)

// checks if the ContentViewPackageEnvironmentResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ContentViewPackageEnvironmentResponse{}

// ContentViewPackageEnvironmentResponse A representation of a PackageEnvironment for Content View search results.
type ContentViewPackageEnvironmentResponse struct {
	PulpHref *string `json:"pulp_href,omitempty"`
	// ID of the environment
	Id string `json:"id"`
	// The name of the environment
	Name string `json:"name"`
	// The description of the environment
	Description string `json:"description"`
	// A list of group ids
	GroupIds interface{} `json:"group_ids"`
	AdditionalProperties map[string]interface{}
}

type _ContentViewPackageEnvironmentResponse ContentViewPackageEnvironmentResponse

// NewContentViewPackageEnvironmentResponse instantiates a new ContentViewPackageEnvironmentResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewContentViewPackageEnvironmentResponse(id string, name string, description string, groupIds interface{}) *ContentViewPackageEnvironmentResponse {
	this := ContentViewPackageEnvironmentResponse{}
	this.Id = id
	this.Name = name
	this.Description = description
	this.GroupIds = groupIds
	return &this
}

// NewContentViewPackageEnvironmentResponseWithDefaults instantiates a new ContentViewPackageEnvironmentResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewContentViewPackageEnvironmentResponseWithDefaults() *ContentViewPackageEnvironmentResponse {
	this := ContentViewPackageEnvironmentResponse{}
	return &this
}

// GetPulpHref returns the PulpHref field value if set, zero value otherwise.
func (o *ContentViewPackageEnvironmentResponse) GetPulpHref() string {
	if o == nil || IsNil(o.PulpHref) {
		var ret string
		return ret
	}
	return *o.PulpHref
}

// GetPulpHrefOk returns a tuple with the PulpHref field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ContentViewPackageEnvironmentResponse) GetPulpHrefOk() (*string, bool) {
	if o == nil || IsNil(o.PulpHref) {
		return nil, false
	}
	return o.PulpHref, true
}

// HasPulpHref returns a boolean if a field has been set.
func (o *ContentViewPackageEnvironmentResponse) HasPulpHref() bool {
	if o != nil && !IsNil(o.PulpHref) {
		return true
	}

	return false
}

// SetPulpHref gets a reference to the given string and assigns it to the PulpHref field.
func (o *ContentViewPackageEnvironmentResponse) SetPulpHref(v string) {
	o.PulpHref = &v
}

// GetId returns the Id field value
func (o *ContentViewPackageEnvironmentResponse) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *ContentViewPackageEnvironmentResponse) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *ContentViewPackageEnvironmentResponse) SetId(v string) {
	o.Id = v
}

// GetName returns the Name field value
func (o *ContentViewPackageEnvironmentResponse) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *ContentViewPackageEnvironmentResponse) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *ContentViewPackageEnvironmentResponse) SetName(v string) {
	o.Name = v
}

// GetDescription returns the Description field value
func (o *ContentViewPackageEnvironmentResponse) GetDescription() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Description
}

// GetDescriptionOk returns a tuple with the Description field value
// and a boolean to check if the value has been set.
func (o *ContentViewPackageEnvironmentResponse) GetDescriptionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Description, true
}

// SetDescription sets field value
func (o *ContentViewPackageEnvironmentResponse) SetDescription(v string) {
	o.Description = v
}

// GetGroupIds returns the GroupIds field value
// If the value is explicit nil, the zero value for interface{} will be returned
func (o *ContentViewPackageEnvironmentResponse) GetGroupIds() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}

	return o.GroupIds
}

// GetGroupIdsOk returns a tuple with the GroupIds field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ContentViewPackageEnvironmentResponse) GetGroupIdsOk() (*interface{}, bool) {
	if o == nil || IsNil(o.GroupIds) {
		return nil, false
	}
	return &o.GroupIds, true
}

// SetGroupIds sets field value
func (o *ContentViewPackageEnvironmentResponse) SetGroupIds(v interface{}) {
	o.GroupIds = v
}

func (o ContentViewPackageEnvironmentResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ContentViewPackageEnvironmentResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.PulpHref) {
		toSerialize["pulp_href"] = o.PulpHref
	}
	toSerialize["id"] = o.Id
	toSerialize["name"] = o.Name
	toSerialize["description"] = o.Description
	if o.GroupIds != nil {
		toSerialize["group_ids"] = o.GroupIds
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *ContentViewPackageEnvironmentResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"name",
		"description",
		"group_ids",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varContentViewPackageEnvironmentResponse := _ContentViewPackageEnvironmentResponse{}

	err = json.Unmarshal(data, &varContentViewPackageEnvironmentResponse)

	if err != nil {
		return err
	}

	*o = ContentViewPackageEnvironmentResponse(varContentViewPackageEnvironmentResponse)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "pulp_href")
		delete(additionalProperties, "id")
		delete(additionalProperties, "name")
		delete(additionalProperties, "description")
		delete(additionalProperties, "group_ids")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableContentViewPackageEnvironmentResponse struct {
	value *ContentViewPackageEnvironmentResponse
	isSet bool
}

func (v NullableContentViewPackageEnvironmentResponse) Get() *ContentViewPackageEnvironmentResponse {
	return v.value
}

func (v *NullableContentViewPackageEnvironmentResponse) Set(val *ContentViewPackageEnvironmentResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableContentViewPackageEnvironmentResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableContentViewPackageEnvironmentResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableContentViewPackageEnvironmentResponse(val *ContentViewPackageEnvironmentResponse) *NullableContentViewPackageEnvironmentResponse {
	return &NullableContentViewPackageEnvironmentResponse{value: val, isSet: true}
}

func (v NullableContentViewPackageEnvironmentResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableContentViewPackageEnvironmentResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


