/*
Pulp 3 API

Fetch, Upload, Organize, and Distribute Software Packages

API version: v3
Contact: pulp-list@redhat.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package zest

import (
	"encoding/json"
	"time"
)

// checks if the MavenMavenIndexPageResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &MavenMavenIndexPageResponse{}

// MavenMavenIndexPageResponse A read-only Serializer for MavenIndexPage.
type MavenMavenIndexPageResponse struct {
	PulpHref *string `json:"pulp_href,omitempty"`
	// The Pulp Resource Name (PRN).
	Prn *string `json:"prn,omitempty"`
	// Timestamp of creation.
	PulpCreated *time.Time `json:"pulp_created,omitempty"`
	// Timestamp of the last time this resource was updated. Note: for immutable resources - like content, repository versions, and publication - pulp_created and pulp_last_updated dates will be the same.
	PulpLastUpdated *time.Time `json:"pulp_last_updated,omitempty"`
	// A dictionary of arbitrary key/value pairs used to describe a specific Content instance.
	PulpLabels *map[string]*string `json:"pulp_labels,omitempty"`
	VulnReport *string `json:"vuln_report,omitempty"`
	// Directory path this page indexes.
	Path *string `json:"path,omitempty"`
	// SHA256 digest of the HTML content.
	Sha256 *string `json:"sha256,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _MavenMavenIndexPageResponse MavenMavenIndexPageResponse

// NewMavenMavenIndexPageResponse instantiates a new MavenMavenIndexPageResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewMavenMavenIndexPageResponse() *MavenMavenIndexPageResponse {
	this := MavenMavenIndexPageResponse{}
	return &this
}

// NewMavenMavenIndexPageResponseWithDefaults instantiates a new MavenMavenIndexPageResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewMavenMavenIndexPageResponseWithDefaults() *MavenMavenIndexPageResponse {
	this := MavenMavenIndexPageResponse{}
	return &this
}

// GetPulpHref returns the PulpHref field value if set, zero value otherwise.
func (o *MavenMavenIndexPageResponse) GetPulpHref() string {
	if o == nil || IsNil(o.PulpHref) {
		var ret string
		return ret
	}
	return *o.PulpHref
}

// GetPulpHrefOk returns a tuple with the PulpHref field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MavenMavenIndexPageResponse) GetPulpHrefOk() (*string, bool) {
	if o == nil || IsNil(o.PulpHref) {
		return nil, false
	}
	return o.PulpHref, true
}

// HasPulpHref returns a boolean if a field has been set.
func (o *MavenMavenIndexPageResponse) HasPulpHref() bool {
	if o != nil && !IsNil(o.PulpHref) {
		return true
	}

	return false
}

// SetPulpHref gets a reference to the given string and assigns it to the PulpHref field.
func (o *MavenMavenIndexPageResponse) SetPulpHref(v string) {
	o.PulpHref = &v
}

// GetPrn returns the Prn field value if set, zero value otherwise.
func (o *MavenMavenIndexPageResponse) GetPrn() string {
	if o == nil || IsNil(o.Prn) {
		var ret string
		return ret
	}
	return *o.Prn
}

// GetPrnOk returns a tuple with the Prn field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MavenMavenIndexPageResponse) GetPrnOk() (*string, bool) {
	if o == nil || IsNil(o.Prn) {
		return nil, false
	}
	return o.Prn, true
}

// HasPrn returns a boolean if a field has been set.
func (o *MavenMavenIndexPageResponse) HasPrn() bool {
	if o != nil && !IsNil(o.Prn) {
		return true
	}

	return false
}

// SetPrn gets a reference to the given string and assigns it to the Prn field.
func (o *MavenMavenIndexPageResponse) SetPrn(v string) {
	o.Prn = &v
}

// GetPulpCreated returns the PulpCreated field value if set, zero value otherwise.
func (o *MavenMavenIndexPageResponse) GetPulpCreated() time.Time {
	if o == nil || IsNil(o.PulpCreated) {
		var ret time.Time
		return ret
	}
	return *o.PulpCreated
}

// GetPulpCreatedOk returns a tuple with the PulpCreated field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MavenMavenIndexPageResponse) GetPulpCreatedOk() (*time.Time, bool) {
	if o == nil || IsNil(o.PulpCreated) {
		return nil, false
	}
	return o.PulpCreated, true
}

// HasPulpCreated returns a boolean if a field has been set.
func (o *MavenMavenIndexPageResponse) HasPulpCreated() bool {
	if o != nil && !IsNil(o.PulpCreated) {
		return true
	}

	return false
}

// SetPulpCreated gets a reference to the given time.Time and assigns it to the PulpCreated field.
func (o *MavenMavenIndexPageResponse) SetPulpCreated(v time.Time) {
	o.PulpCreated = &v
}

// GetPulpLastUpdated returns the PulpLastUpdated field value if set, zero value otherwise.
func (o *MavenMavenIndexPageResponse) GetPulpLastUpdated() time.Time {
	if o == nil || IsNil(o.PulpLastUpdated) {
		var ret time.Time
		return ret
	}
	return *o.PulpLastUpdated
}

// GetPulpLastUpdatedOk returns a tuple with the PulpLastUpdated field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MavenMavenIndexPageResponse) GetPulpLastUpdatedOk() (*time.Time, bool) {
	if o == nil || IsNil(o.PulpLastUpdated) {
		return nil, false
	}
	return o.PulpLastUpdated, true
}

// HasPulpLastUpdated returns a boolean if a field has been set.
func (o *MavenMavenIndexPageResponse) HasPulpLastUpdated() bool {
	if o != nil && !IsNil(o.PulpLastUpdated) {
		return true
	}

	return false
}

// SetPulpLastUpdated gets a reference to the given time.Time and assigns it to the PulpLastUpdated field.
func (o *MavenMavenIndexPageResponse) SetPulpLastUpdated(v time.Time) {
	o.PulpLastUpdated = &v
}

// GetPulpLabels returns the PulpLabels field value if set, zero value otherwise.
func (o *MavenMavenIndexPageResponse) GetPulpLabels() map[string]*string {
	if o == nil || IsNil(o.PulpLabels) {
		var ret map[string]*string
		return ret
	}
	return *o.PulpLabels
}

// GetPulpLabelsOk returns a tuple with the PulpLabels field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MavenMavenIndexPageResponse) GetPulpLabelsOk() (*map[string]*string, bool) {
	if o == nil || IsNil(o.PulpLabels) {
		return nil, false
	}
	return o.PulpLabels, true
}

// HasPulpLabels returns a boolean if a field has been set.
func (o *MavenMavenIndexPageResponse) HasPulpLabels() bool {
	if o != nil && !IsNil(o.PulpLabels) {
		return true
	}

	return false
}

// SetPulpLabels gets a reference to the given map[string]*string and assigns it to the PulpLabels field.
func (o *MavenMavenIndexPageResponse) SetPulpLabels(v map[string]*string) {
	o.PulpLabels = &v
}

// GetVulnReport returns the VulnReport field value if set, zero value otherwise.
func (o *MavenMavenIndexPageResponse) GetVulnReport() string {
	if o == nil || IsNil(o.VulnReport) {
		var ret string
		return ret
	}
	return *o.VulnReport
}

// GetVulnReportOk returns a tuple with the VulnReport field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MavenMavenIndexPageResponse) GetVulnReportOk() (*string, bool) {
	if o == nil || IsNil(o.VulnReport) {
		return nil, false
	}
	return o.VulnReport, true
}

// HasVulnReport returns a boolean if a field has been set.
func (o *MavenMavenIndexPageResponse) HasVulnReport() bool {
	if o != nil && !IsNil(o.VulnReport) {
		return true
	}

	return false
}

// SetVulnReport gets a reference to the given string and assigns it to the VulnReport field.
func (o *MavenMavenIndexPageResponse) SetVulnReport(v string) {
	o.VulnReport = &v
}

// GetPath returns the Path field value if set, zero value otherwise.
func (o *MavenMavenIndexPageResponse) GetPath() string {
	if o == nil || IsNil(o.Path) {
		var ret string
		return ret
	}
	return *o.Path
}

// GetPathOk returns a tuple with the Path field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MavenMavenIndexPageResponse) GetPathOk() (*string, bool) {
	if o == nil || IsNil(o.Path) {
		return nil, false
	}
	return o.Path, true
}

// HasPath returns a boolean if a field has been set.
func (o *MavenMavenIndexPageResponse) HasPath() bool {
	if o != nil && !IsNil(o.Path) {
		return true
	}

	return false
}

// SetPath gets a reference to the given string and assigns it to the Path field.
func (o *MavenMavenIndexPageResponse) SetPath(v string) {
	o.Path = &v
}

// GetSha256 returns the Sha256 field value if set, zero value otherwise.
func (o *MavenMavenIndexPageResponse) GetSha256() string {
	if o == nil || IsNil(o.Sha256) {
		var ret string
		return ret
	}
	return *o.Sha256
}

// GetSha256Ok returns a tuple with the Sha256 field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MavenMavenIndexPageResponse) GetSha256Ok() (*string, bool) {
	if o == nil || IsNil(o.Sha256) {
		return nil, false
	}
	return o.Sha256, true
}

// HasSha256 returns a boolean if a field has been set.
func (o *MavenMavenIndexPageResponse) HasSha256() bool {
	if o != nil && !IsNil(o.Sha256) {
		return true
	}

	return false
}

// SetSha256 gets a reference to the given string and assigns it to the Sha256 field.
func (o *MavenMavenIndexPageResponse) SetSha256(v string) {
	o.Sha256 = &v
}

func (o MavenMavenIndexPageResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o MavenMavenIndexPageResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.PulpHref) {
		toSerialize["pulp_href"] = o.PulpHref
	}
	if !IsNil(o.Prn) {
		toSerialize["prn"] = o.Prn
	}
	if !IsNil(o.PulpCreated) {
		toSerialize["pulp_created"] = o.PulpCreated
	}
	if !IsNil(o.PulpLastUpdated) {
		toSerialize["pulp_last_updated"] = o.PulpLastUpdated
	}
	if !IsNil(o.PulpLabels) {
		toSerialize["pulp_labels"] = o.PulpLabels
	}
	if !IsNil(o.VulnReport) {
		toSerialize["vuln_report"] = o.VulnReport
	}
	if !IsNil(o.Path) {
		toSerialize["path"] = o.Path
	}
	if !IsNil(o.Sha256) {
		toSerialize["sha256"] = o.Sha256
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *MavenMavenIndexPageResponse) UnmarshalJSON(data []byte) (err error) {
	varMavenMavenIndexPageResponse := _MavenMavenIndexPageResponse{}

	err = json.Unmarshal(data, &varMavenMavenIndexPageResponse)

	if err != nil {
		return err
	}

	*o = MavenMavenIndexPageResponse(varMavenMavenIndexPageResponse)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "pulp_href")
		delete(additionalProperties, "prn")
		delete(additionalProperties, "pulp_created")
		delete(additionalProperties, "pulp_last_updated")
		delete(additionalProperties, "pulp_labels")
		delete(additionalProperties, "vuln_report")
		delete(additionalProperties, "path")
		delete(additionalProperties, "sha256")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableMavenMavenIndexPageResponse struct {
	value *MavenMavenIndexPageResponse
	isSet bool
}

func (v NullableMavenMavenIndexPageResponse) Get() *MavenMavenIndexPageResponse {
	return v.value
}

func (v *NullableMavenMavenIndexPageResponse) Set(val *MavenMavenIndexPageResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableMavenMavenIndexPageResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableMavenMavenIndexPageResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMavenMavenIndexPageResponse(val *MavenMavenIndexPageResponse) *NullableMavenMavenIndexPageResponse {
	return &NullableMavenMavenIndexPageResponse{value: val, isSet: true}
}

func (v NullableMavenMavenIndexPageResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableMavenMavenIndexPageResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


