/*
Pulp 3 API

Fetch, Upload, Organize, and Distribute Software Packages

API version: v3
Contact: pulp-list@redhat.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package zest

import (
	"encoding/json"
	"time"
	"fmt"
)

// checks if the MavenRepositoryFlatPackageResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &MavenRepositoryFlatPackageResponse{}

// MavenRepositoryFlatPackageResponse One MavenPackage in a repository version. ``version`` is stored unchanged.
type MavenRepositoryFlatPackageResponse struct {
	// Maven groupId.
	GroupId string `json:"group_id"`
	// Maven artifactId.
	ArtifactId string `json:"artifact_id"`
	// Version stored on the MavenPackage, including any rebuild suffix.
	Version string `json:"version"`
	// When this GAV entered the repository version: RepositoryContent.pulp_created, falling back to the content unit's pulp_created.
	LastUpdated time.Time `json:"last_updated"`
	// Description from the POM. Empty when the POM has none.
	Description string `json:"description"`
	// Licenses from the POM. Empty when the POM has none.
	Licenses []MavenPackageLicenseResponse `json:"licenses"`
	AdditionalProperties map[string]interface{}
}

type _MavenRepositoryFlatPackageResponse MavenRepositoryFlatPackageResponse

// NewMavenRepositoryFlatPackageResponse instantiates a new MavenRepositoryFlatPackageResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewMavenRepositoryFlatPackageResponse(groupId string, artifactId string, version string, lastUpdated time.Time, description string, licenses []MavenPackageLicenseResponse) *MavenRepositoryFlatPackageResponse {
	this := MavenRepositoryFlatPackageResponse{}
	this.GroupId = groupId
	this.ArtifactId = artifactId
	this.Version = version
	this.LastUpdated = lastUpdated
	this.Description = description
	this.Licenses = licenses
	return &this
}

// NewMavenRepositoryFlatPackageResponseWithDefaults instantiates a new MavenRepositoryFlatPackageResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewMavenRepositoryFlatPackageResponseWithDefaults() *MavenRepositoryFlatPackageResponse {
	this := MavenRepositoryFlatPackageResponse{}
	return &this
}

// GetGroupId returns the GroupId field value
func (o *MavenRepositoryFlatPackageResponse) GetGroupId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.GroupId
}

// GetGroupIdOk returns a tuple with the GroupId field value
// and a boolean to check if the value has been set.
func (o *MavenRepositoryFlatPackageResponse) GetGroupIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.GroupId, true
}

// SetGroupId sets field value
func (o *MavenRepositoryFlatPackageResponse) SetGroupId(v string) {
	o.GroupId = v
}

// GetArtifactId returns the ArtifactId field value
func (o *MavenRepositoryFlatPackageResponse) GetArtifactId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ArtifactId
}

// GetArtifactIdOk returns a tuple with the ArtifactId field value
// and a boolean to check if the value has been set.
func (o *MavenRepositoryFlatPackageResponse) GetArtifactIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ArtifactId, true
}

// SetArtifactId sets field value
func (o *MavenRepositoryFlatPackageResponse) SetArtifactId(v string) {
	o.ArtifactId = v
}

// GetVersion returns the Version field value
func (o *MavenRepositoryFlatPackageResponse) GetVersion() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Version
}

// GetVersionOk returns a tuple with the Version field value
// and a boolean to check if the value has been set.
func (o *MavenRepositoryFlatPackageResponse) GetVersionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Version, true
}

// SetVersion sets field value
func (o *MavenRepositoryFlatPackageResponse) SetVersion(v string) {
	o.Version = v
}

// GetLastUpdated returns the LastUpdated field value
func (o *MavenRepositoryFlatPackageResponse) GetLastUpdated() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.LastUpdated
}

// GetLastUpdatedOk returns a tuple with the LastUpdated field value
// and a boolean to check if the value has been set.
func (o *MavenRepositoryFlatPackageResponse) GetLastUpdatedOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.LastUpdated, true
}

// SetLastUpdated sets field value
func (o *MavenRepositoryFlatPackageResponse) SetLastUpdated(v time.Time) {
	o.LastUpdated = v
}

// GetDescription returns the Description field value
func (o *MavenRepositoryFlatPackageResponse) GetDescription() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Description
}

// GetDescriptionOk returns a tuple with the Description field value
// and a boolean to check if the value has been set.
func (o *MavenRepositoryFlatPackageResponse) GetDescriptionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Description, true
}

// SetDescription sets field value
func (o *MavenRepositoryFlatPackageResponse) SetDescription(v string) {
	o.Description = v
}

// GetLicenses returns the Licenses field value
func (o *MavenRepositoryFlatPackageResponse) GetLicenses() []MavenPackageLicenseResponse {
	if o == nil {
		var ret []MavenPackageLicenseResponse
		return ret
	}

	return o.Licenses
}

// GetLicensesOk returns a tuple with the Licenses field value
// and a boolean to check if the value has been set.
func (o *MavenRepositoryFlatPackageResponse) GetLicensesOk() ([]MavenPackageLicenseResponse, bool) {
	if o == nil {
		return nil, false
	}
	return o.Licenses, true
}

// SetLicenses sets field value
func (o *MavenRepositoryFlatPackageResponse) SetLicenses(v []MavenPackageLicenseResponse) {
	o.Licenses = v
}

func (o MavenRepositoryFlatPackageResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o MavenRepositoryFlatPackageResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["group_id"] = o.GroupId
	toSerialize["artifact_id"] = o.ArtifactId
	toSerialize["version"] = o.Version
	toSerialize["last_updated"] = o.LastUpdated
	toSerialize["description"] = o.Description
	toSerialize["licenses"] = o.Licenses

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *MavenRepositoryFlatPackageResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"group_id",
		"artifact_id",
		"version",
		"last_updated",
		"description",
		"licenses",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varMavenRepositoryFlatPackageResponse := _MavenRepositoryFlatPackageResponse{}

	err = json.Unmarshal(data, &varMavenRepositoryFlatPackageResponse)

	if err != nil {
		return err
	}

	*o = MavenRepositoryFlatPackageResponse(varMavenRepositoryFlatPackageResponse)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "group_id")
		delete(additionalProperties, "artifact_id")
		delete(additionalProperties, "version")
		delete(additionalProperties, "last_updated")
		delete(additionalProperties, "description")
		delete(additionalProperties, "licenses")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableMavenRepositoryFlatPackageResponse struct {
	value *MavenRepositoryFlatPackageResponse
	isSet bool
}

func (v NullableMavenRepositoryFlatPackageResponse) Get() *MavenRepositoryFlatPackageResponse {
	return v.value
}

func (v *NullableMavenRepositoryFlatPackageResponse) Set(val *MavenRepositoryFlatPackageResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableMavenRepositoryFlatPackageResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableMavenRepositoryFlatPackageResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMavenRepositoryFlatPackageResponse(val *MavenRepositoryFlatPackageResponse) *NullableMavenRepositoryFlatPackageResponse {
	return &NullableMavenRepositoryFlatPackageResponse{value: val, isSet: true}
}

func (v NullableMavenRepositoryFlatPackageResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableMavenRepositoryFlatPackageResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


