/*
Pulp 3 API

Fetch, Upload, Organize, and Distribute Software Packages

API version: v3
Contact: pulp-list@redhat.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package zest

import (
	"encoding/json"
	"time"
	"fmt"
)

// checks if the MavenPackageReleaseResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &MavenPackageReleaseResponse{}

// MavenPackageReleaseResponse One logical version on the repository package index.
type MavenPackageReleaseResponse struct {
	// Logical version key (rebuild suffix stripped).
	Version string `json:"version"`
	// Rebuild/release qualifier within the version line (e.g. rhlw-00003). Empty when the selected unit has no rebuild suffix.
	Release string `json:"release"`
	// When this logical version entered the repository: RepositoryContent.pulp_created of the newest rebuild, falling back to the content unit's pulp_created.
	CreatedAt time.Time `json:"created_at"`
	AdditionalProperties map[string]interface{}
}

type _MavenPackageReleaseResponse MavenPackageReleaseResponse

// NewMavenPackageReleaseResponse instantiates a new MavenPackageReleaseResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewMavenPackageReleaseResponse(version string, release string, createdAt time.Time) *MavenPackageReleaseResponse {
	this := MavenPackageReleaseResponse{}
	this.Version = version
	this.Release = release
	this.CreatedAt = createdAt
	return &this
}

// NewMavenPackageReleaseResponseWithDefaults instantiates a new MavenPackageReleaseResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewMavenPackageReleaseResponseWithDefaults() *MavenPackageReleaseResponse {
	this := MavenPackageReleaseResponse{}
	return &this
}

// GetVersion returns the Version field value
func (o *MavenPackageReleaseResponse) GetVersion() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Version
}

// GetVersionOk returns a tuple with the Version field value
// and a boolean to check if the value has been set.
func (o *MavenPackageReleaseResponse) GetVersionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Version, true
}

// SetVersion sets field value
func (o *MavenPackageReleaseResponse) SetVersion(v string) {
	o.Version = v
}

// GetRelease returns the Release field value
func (o *MavenPackageReleaseResponse) GetRelease() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Release
}

// GetReleaseOk returns a tuple with the Release field value
// and a boolean to check if the value has been set.
func (o *MavenPackageReleaseResponse) GetReleaseOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Release, true
}

// SetRelease sets field value
func (o *MavenPackageReleaseResponse) SetRelease(v string) {
	o.Release = v
}

// GetCreatedAt returns the CreatedAt field value
func (o *MavenPackageReleaseResponse) GetCreatedAt() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value
// and a boolean to check if the value has been set.
func (o *MavenPackageReleaseResponse) GetCreatedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CreatedAt, true
}

// SetCreatedAt sets field value
func (o *MavenPackageReleaseResponse) SetCreatedAt(v time.Time) {
	o.CreatedAt = v
}

func (o MavenPackageReleaseResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o MavenPackageReleaseResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["version"] = o.Version
	toSerialize["release"] = o.Release
	toSerialize["created_at"] = o.CreatedAt

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *MavenPackageReleaseResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"version",
		"release",
		"created_at",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varMavenPackageReleaseResponse := _MavenPackageReleaseResponse{}

	err = json.Unmarshal(data, &varMavenPackageReleaseResponse)

	if err != nil {
		return err
	}

	*o = MavenPackageReleaseResponse(varMavenPackageReleaseResponse)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "version")
		delete(additionalProperties, "release")
		delete(additionalProperties, "created_at")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableMavenPackageReleaseResponse struct {
	value *MavenPackageReleaseResponse
	isSet bool
}

func (v NullableMavenPackageReleaseResponse) Get() *MavenPackageReleaseResponse {
	return v.value
}

func (v *NullableMavenPackageReleaseResponse) Set(val *MavenPackageReleaseResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableMavenPackageReleaseResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableMavenPackageReleaseResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMavenPackageReleaseResponse(val *MavenPackageReleaseResponse) *NullableMavenPackageReleaseResponse {
	return &NullableMavenPackageReleaseResponse{value: val, isSet: true}
}

func (v NullableMavenPackageReleaseResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableMavenPackageReleaseResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


