/*
Pulp 3 API

Fetch, Upload, Organize, and Distribute Software Packages

API version: v3
Contact: pulp-list@redhat.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package zest

import (
	"encoding/json"
)

// checks if the PatchedserviceContentView type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PatchedserviceContentView{}

// PatchedserviceContentView Serializer for a ContentView -- a named, persistable scope composed of Distributions thatmay span multiple domains, used to search across their content without exposing rawrepository version hrefs on every request.
type PatchedserviceContentView struct {
	// A unique name for this content view.
	Name *string `json:"name,omitempty"`
	// An optional description of this content view.
	Description NullableString `json:"description,omitempty"`
	PulpLabels *map[string]*string `json:"pulp_labels,omitempty"`
	// Distributions this content view searches across. May reference distributions belonging to any domain the user has read access to, not just this content view's own domain.
	Distributions []string `json:"distributions,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _PatchedserviceContentView PatchedserviceContentView

// NewPatchedserviceContentView instantiates a new PatchedserviceContentView object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPatchedserviceContentView() *PatchedserviceContentView {
	this := PatchedserviceContentView{}
	return &this
}

// NewPatchedserviceContentViewWithDefaults instantiates a new PatchedserviceContentView object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPatchedserviceContentViewWithDefaults() *PatchedserviceContentView {
	this := PatchedserviceContentView{}
	return &this
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *PatchedserviceContentView) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PatchedserviceContentView) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *PatchedserviceContentView) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *PatchedserviceContentView) SetName(v string) {
	o.Name = &v
}

// GetDescription returns the Description field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *PatchedserviceContentView) GetDescription() string {
	if o == nil || IsNil(o.Description.Get()) {
		var ret string
		return ret
	}
	return *o.Description.Get()
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *PatchedserviceContentView) GetDescriptionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Description.Get(), o.Description.IsSet()
}

// HasDescription returns a boolean if a field has been set.
func (o *PatchedserviceContentView) HasDescription() bool {
	if o != nil && o.Description.IsSet() {
		return true
	}

	return false
}

// SetDescription gets a reference to the given NullableString and assigns it to the Description field.
func (o *PatchedserviceContentView) SetDescription(v string) {
	o.Description.Set(&v)
}
// SetDescriptionNil sets the value for Description to be an explicit nil
func (o *PatchedserviceContentView) SetDescriptionNil() {
	o.Description.Set(nil)
}

// UnsetDescription ensures that no value is present for Description, not even an explicit nil
func (o *PatchedserviceContentView) UnsetDescription() {
	o.Description.Unset()
}

// GetPulpLabels returns the PulpLabels field value if set, zero value otherwise.
func (o *PatchedserviceContentView) GetPulpLabels() map[string]*string {
	if o == nil || IsNil(o.PulpLabels) {
		var ret map[string]*string
		return ret
	}
	return *o.PulpLabels
}

// GetPulpLabelsOk returns a tuple with the PulpLabels field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PatchedserviceContentView) GetPulpLabelsOk() (*map[string]*string, bool) {
	if o == nil || IsNil(o.PulpLabels) {
		return nil, false
	}
	return o.PulpLabels, true
}

// HasPulpLabels returns a boolean if a field has been set.
func (o *PatchedserviceContentView) HasPulpLabels() bool {
	if o != nil && !IsNil(o.PulpLabels) {
		return true
	}

	return false
}

// SetPulpLabels gets a reference to the given map[string]*string and assigns it to the PulpLabels field.
func (o *PatchedserviceContentView) SetPulpLabels(v map[string]*string) {
	o.PulpLabels = &v
}

// GetDistributions returns the Distributions field value if set, zero value otherwise.
func (o *PatchedserviceContentView) GetDistributions() []string {
	if o == nil || IsNil(o.Distributions) {
		var ret []string
		return ret
	}
	return o.Distributions
}

// GetDistributionsOk returns a tuple with the Distributions field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PatchedserviceContentView) GetDistributionsOk() ([]string, bool) {
	if o == nil || IsNil(o.Distributions) {
		return nil, false
	}
	return o.Distributions, true
}

// HasDistributions returns a boolean if a field has been set.
func (o *PatchedserviceContentView) HasDistributions() bool {
	if o != nil && !IsNil(o.Distributions) {
		return true
	}

	return false
}

// SetDistributions gets a reference to the given []string and assigns it to the Distributions field.
func (o *PatchedserviceContentView) SetDistributions(v []string) {
	o.Distributions = v
}

func (o PatchedserviceContentView) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PatchedserviceContentView) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if o.Description.IsSet() {
		toSerialize["description"] = o.Description.Get()
	}
	if !IsNil(o.PulpLabels) {
		toSerialize["pulp_labels"] = o.PulpLabels
	}
	if !IsNil(o.Distributions) {
		toSerialize["distributions"] = o.Distributions
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *PatchedserviceContentView) UnmarshalJSON(data []byte) (err error) {
	varPatchedserviceContentView := _PatchedserviceContentView{}

	err = json.Unmarshal(data, &varPatchedserviceContentView)

	if err != nil {
		return err
	}

	*o = PatchedserviceContentView(varPatchedserviceContentView)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "name")
		delete(additionalProperties, "description")
		delete(additionalProperties, "pulp_labels")
		delete(additionalProperties, "distributions")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullablePatchedserviceContentView struct {
	value *PatchedserviceContentView
	isSet bool
}

func (v NullablePatchedserviceContentView) Get() *PatchedserviceContentView {
	return v.value
}

func (v *NullablePatchedserviceContentView) Set(val *PatchedserviceContentView) {
	v.value = val
	v.isSet = true
}

func (v NullablePatchedserviceContentView) IsSet() bool {
	return v.isSet
}

func (v *NullablePatchedserviceContentView) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePatchedserviceContentView(val *PatchedserviceContentView) *NullablePatchedserviceContentView {
	return &NullablePatchedserviceContentView{value: val, isSet: true}
}

func (v NullablePatchedserviceContentView) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePatchedserviceContentView) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


