/*
Pulp 3 API

Fetch, Upload, Organize, and Distribute Software Packages

API version: v3
Contact: pulp-list@redhat.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package zest

import (
	"encoding/json"
	"fmt"
)

// checks if the Yank type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &Yank{}

// Yank A Serializer for yank/unyank requests (PEP 592).
type Yank struct {
	// The name of the package to yank or unyank.
	Name string `json:"name"`
	// The version of the package to yank or unyank.
	Version string `json:"version"`
	// The reason for yanking the package version.
	YankedReason *string `json:"yanked_reason,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _Yank Yank

// NewYank instantiates a new Yank object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewYank(name string, version string) *Yank {
	this := Yank{}
	this.Name = name
	this.Version = version
	var yankedReason string = ""
	this.YankedReason = &yankedReason
	return &this
}

// NewYankWithDefaults instantiates a new Yank object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewYankWithDefaults() *Yank {
	this := Yank{}
	var yankedReason string = ""
	this.YankedReason = &yankedReason
	return &this
}

// GetName returns the Name field value
func (o *Yank) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *Yank) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *Yank) SetName(v string) {
	o.Name = v
}

// GetVersion returns the Version field value
func (o *Yank) GetVersion() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Version
}

// GetVersionOk returns a tuple with the Version field value
// and a boolean to check if the value has been set.
func (o *Yank) GetVersionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Version, true
}

// SetVersion sets field value
func (o *Yank) SetVersion(v string) {
	o.Version = v
}

// GetYankedReason returns the YankedReason field value if set, zero value otherwise.
func (o *Yank) GetYankedReason() string {
	if o == nil || IsNil(o.YankedReason) {
		var ret string
		return ret
	}
	return *o.YankedReason
}

// GetYankedReasonOk returns a tuple with the YankedReason field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Yank) GetYankedReasonOk() (*string, bool) {
	if o == nil || IsNil(o.YankedReason) {
		return nil, false
	}
	return o.YankedReason, true
}

// HasYankedReason returns a boolean if a field has been set.
func (o *Yank) HasYankedReason() bool {
	if o != nil && !IsNil(o.YankedReason) {
		return true
	}

	return false
}

// SetYankedReason gets a reference to the given string and assigns it to the YankedReason field.
func (o *Yank) SetYankedReason(v string) {
	o.YankedReason = &v
}

func (o Yank) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o Yank) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["name"] = o.Name
	toSerialize["version"] = o.Version
	if !IsNil(o.YankedReason) {
		toSerialize["yanked_reason"] = o.YankedReason
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *Yank) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"name",
		"version",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varYank := _Yank{}

	err = json.Unmarshal(data, &varYank)

	if err != nil {
		return err
	}

	*o = Yank(varYank)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "name")
		delete(additionalProperties, "version")
		delete(additionalProperties, "yanked_reason")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableYank struct {
	value *Yank
	isSet bool
}

func (v NullableYank) Get() *Yank {
	return v.value
}

func (v *NullableYank) Set(val *Yank) {
	v.value = val
	v.isSet = true
}

func (v NullableYank) IsSet() bool {
	return v.isSet
}

func (v *NullableYank) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableYank(val *Yank) *NullableYank {
	return &NullableYank{value: val, isSet: true}
}

func (v NullableYank) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableYank) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


