/*
Pulp 3 API

Fetch, Upload, Organize, and Distribute Software Packages

API version: v3
Contact: pulp-list@redhat.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package zest

import (
	"encoding/json"
	"fmt"
)

// checks if the ContentViewPackageResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ContentViewPackageResponse{}

// ContentViewPackageResponse A lightweight representation of a Package for Content View search results.Used by the ``packages/`` (typeahead) and ``packages/list/`` search endpoints. Instancesmay originate from any domain the ContentView's Distributions span, so ``pulp_href``resolves per-object using each Package's own domain.
type ContentViewPackageResponse struct {
	PulpHref *string `json:"pulp_href,omitempty"`
	// Name of the package
	Name string `json:"name"`
	// The package's epoch
	Epoch string `json:"epoch"`
	// The version of the package
	Version string `json:"version"`
	// The release of the package
	Release string `json:"release"`
	// The target architecture for the package
	Arch string `json:"arch"`
	// Short description of the packaged software
	Summary string `json:"summary"`
	// In-depth description of the package
	Description string `json:"description"`
	// Type of checksum, e.g. 'sha256'
	ChecksumType string `json:"checksum_type"`
	// Checksum of the package file
	PkgId string `json:"pkgId"`
	// URL with more information about the package
	Url string `json:"url"`
	// Relative location of the package
	LocationHref string `json:"location_href"`
	// Whether the package is modular
	IsModular bool `json:"is_modular"`
	AdditionalProperties map[string]interface{}
}

type _ContentViewPackageResponse ContentViewPackageResponse

// NewContentViewPackageResponse instantiates a new ContentViewPackageResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewContentViewPackageResponse(name string, epoch string, version string, release string, arch string, summary string, description string, checksumType string, pkgId string, url string, locationHref string, isModular bool) *ContentViewPackageResponse {
	this := ContentViewPackageResponse{}
	this.Name = name
	this.Epoch = epoch
	this.Version = version
	this.Release = release
	this.Arch = arch
	this.Summary = summary
	this.Description = description
	this.ChecksumType = checksumType
	this.PkgId = pkgId
	this.Url = url
	this.LocationHref = locationHref
	this.IsModular = isModular
	return &this
}

// NewContentViewPackageResponseWithDefaults instantiates a new ContentViewPackageResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewContentViewPackageResponseWithDefaults() *ContentViewPackageResponse {
	this := ContentViewPackageResponse{}
	return &this
}

// GetPulpHref returns the PulpHref field value if set, zero value otherwise.
func (o *ContentViewPackageResponse) GetPulpHref() string {
	if o == nil || IsNil(o.PulpHref) {
		var ret string
		return ret
	}
	return *o.PulpHref
}

// GetPulpHrefOk returns a tuple with the PulpHref field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ContentViewPackageResponse) GetPulpHrefOk() (*string, bool) {
	if o == nil || IsNil(o.PulpHref) {
		return nil, false
	}
	return o.PulpHref, true
}

// HasPulpHref returns a boolean if a field has been set.
func (o *ContentViewPackageResponse) HasPulpHref() bool {
	if o != nil && !IsNil(o.PulpHref) {
		return true
	}

	return false
}

// SetPulpHref gets a reference to the given string and assigns it to the PulpHref field.
func (o *ContentViewPackageResponse) SetPulpHref(v string) {
	o.PulpHref = &v
}

// GetName returns the Name field value
func (o *ContentViewPackageResponse) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *ContentViewPackageResponse) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *ContentViewPackageResponse) SetName(v string) {
	o.Name = v
}

// GetEpoch returns the Epoch field value
func (o *ContentViewPackageResponse) GetEpoch() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Epoch
}

// GetEpochOk returns a tuple with the Epoch field value
// and a boolean to check if the value has been set.
func (o *ContentViewPackageResponse) GetEpochOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Epoch, true
}

// SetEpoch sets field value
func (o *ContentViewPackageResponse) SetEpoch(v string) {
	o.Epoch = v
}

// GetVersion returns the Version field value
func (o *ContentViewPackageResponse) GetVersion() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Version
}

// GetVersionOk returns a tuple with the Version field value
// and a boolean to check if the value has been set.
func (o *ContentViewPackageResponse) GetVersionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Version, true
}

// SetVersion sets field value
func (o *ContentViewPackageResponse) SetVersion(v string) {
	o.Version = v
}

// GetRelease returns the Release field value
func (o *ContentViewPackageResponse) GetRelease() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Release
}

// GetReleaseOk returns a tuple with the Release field value
// and a boolean to check if the value has been set.
func (o *ContentViewPackageResponse) GetReleaseOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Release, true
}

// SetRelease sets field value
func (o *ContentViewPackageResponse) SetRelease(v string) {
	o.Release = v
}

// GetArch returns the Arch field value
func (o *ContentViewPackageResponse) GetArch() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Arch
}

// GetArchOk returns a tuple with the Arch field value
// and a boolean to check if the value has been set.
func (o *ContentViewPackageResponse) GetArchOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Arch, true
}

// SetArch sets field value
func (o *ContentViewPackageResponse) SetArch(v string) {
	o.Arch = v
}

// GetSummary returns the Summary field value
func (o *ContentViewPackageResponse) GetSummary() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Summary
}

// GetSummaryOk returns a tuple with the Summary field value
// and a boolean to check if the value has been set.
func (o *ContentViewPackageResponse) GetSummaryOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Summary, true
}

// SetSummary sets field value
func (o *ContentViewPackageResponse) SetSummary(v string) {
	o.Summary = v
}

// GetDescription returns the Description field value
func (o *ContentViewPackageResponse) GetDescription() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Description
}

// GetDescriptionOk returns a tuple with the Description field value
// and a boolean to check if the value has been set.
func (o *ContentViewPackageResponse) GetDescriptionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Description, true
}

// SetDescription sets field value
func (o *ContentViewPackageResponse) SetDescription(v string) {
	o.Description = v
}

// GetChecksumType returns the ChecksumType field value
func (o *ContentViewPackageResponse) GetChecksumType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ChecksumType
}

// GetChecksumTypeOk returns a tuple with the ChecksumType field value
// and a boolean to check if the value has been set.
func (o *ContentViewPackageResponse) GetChecksumTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ChecksumType, true
}

// SetChecksumType sets field value
func (o *ContentViewPackageResponse) SetChecksumType(v string) {
	o.ChecksumType = v
}

// GetPkgId returns the PkgId field value
func (o *ContentViewPackageResponse) GetPkgId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.PkgId
}

// GetPkgIdOk returns a tuple with the PkgId field value
// and a boolean to check if the value has been set.
func (o *ContentViewPackageResponse) GetPkgIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.PkgId, true
}

// SetPkgId sets field value
func (o *ContentViewPackageResponse) SetPkgId(v string) {
	o.PkgId = v
}

// GetUrl returns the Url field value
func (o *ContentViewPackageResponse) GetUrl() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Url
}

// GetUrlOk returns a tuple with the Url field value
// and a boolean to check if the value has been set.
func (o *ContentViewPackageResponse) GetUrlOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Url, true
}

// SetUrl sets field value
func (o *ContentViewPackageResponse) SetUrl(v string) {
	o.Url = v
}

// GetLocationHref returns the LocationHref field value
func (o *ContentViewPackageResponse) GetLocationHref() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.LocationHref
}

// GetLocationHrefOk returns a tuple with the LocationHref field value
// and a boolean to check if the value has been set.
func (o *ContentViewPackageResponse) GetLocationHrefOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.LocationHref, true
}

// SetLocationHref sets field value
func (o *ContentViewPackageResponse) SetLocationHref(v string) {
	o.LocationHref = v
}

// GetIsModular returns the IsModular field value
func (o *ContentViewPackageResponse) GetIsModular() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.IsModular
}

// GetIsModularOk returns a tuple with the IsModular field value
// and a boolean to check if the value has been set.
func (o *ContentViewPackageResponse) GetIsModularOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.IsModular, true
}

// SetIsModular sets field value
func (o *ContentViewPackageResponse) SetIsModular(v bool) {
	o.IsModular = v
}

func (o ContentViewPackageResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ContentViewPackageResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.PulpHref) {
		toSerialize["pulp_href"] = o.PulpHref
	}
	toSerialize["name"] = o.Name
	toSerialize["epoch"] = o.Epoch
	toSerialize["version"] = o.Version
	toSerialize["release"] = o.Release
	toSerialize["arch"] = o.Arch
	toSerialize["summary"] = o.Summary
	toSerialize["description"] = o.Description
	toSerialize["checksum_type"] = o.ChecksumType
	toSerialize["pkgId"] = o.PkgId
	toSerialize["url"] = o.Url
	toSerialize["location_href"] = o.LocationHref
	toSerialize["is_modular"] = o.IsModular

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *ContentViewPackageResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"name",
		"epoch",
		"version",
		"release",
		"arch",
		"summary",
		"description",
		"checksum_type",
		"pkgId",
		"url",
		"location_href",
		"is_modular",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varContentViewPackageResponse := _ContentViewPackageResponse{}

	err = json.Unmarshal(data, &varContentViewPackageResponse)

	if err != nil {
		return err
	}

	*o = ContentViewPackageResponse(varContentViewPackageResponse)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "pulp_href")
		delete(additionalProperties, "name")
		delete(additionalProperties, "epoch")
		delete(additionalProperties, "version")
		delete(additionalProperties, "release")
		delete(additionalProperties, "arch")
		delete(additionalProperties, "summary")
		delete(additionalProperties, "description")
		delete(additionalProperties, "checksum_type")
		delete(additionalProperties, "pkgId")
		delete(additionalProperties, "url")
		delete(additionalProperties, "location_href")
		delete(additionalProperties, "is_modular")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableContentViewPackageResponse struct {
	value *ContentViewPackageResponse
	isSet bool
}

func (v NullableContentViewPackageResponse) Get() *ContentViewPackageResponse {
	return v.value
}

func (v *NullableContentViewPackageResponse) Set(val *ContentViewPackageResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableContentViewPackageResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableContentViewPackageResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableContentViewPackageResponse(val *ContentViewPackageResponse) *NullableContentViewPackageResponse {
	return &NullableContentViewPackageResponse{value: val, isSet: true}
}

func (v NullableContentViewPackageResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableContentViewPackageResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


