/*
Pulp 3 API

Fetch, Upload, Organize, and Distribute Software Packages

API version: v3
Contact: pulp-list@redhat.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package zest

import (
	"encoding/json"
	"fmt"
)

// checks if the PublicDebugAuthenticationHeadersResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PublicDebugAuthenticationHeadersResponse{}

// PublicDebugAuthenticationHeadersResponse Safe, non-sensitive diagnostics returned by the public auth debug endpoint.
type PublicDebugAuthenticationHeadersResponse struct {
	XRhIdentityPresent bool `json:"x_rh_identity_present"`
	// Whether the trusted X-Pulp-VPN-Verified assertion reached Pulp.
	XPulpVpnVerified bool `json:"x_pulp_vpn_verified"`
	XPulpVpnAccessPresent bool `json:"x_pulp_vpn_access_present"`
	AdditionalProperties map[string]interface{}
}

type _PublicDebugAuthenticationHeadersResponse PublicDebugAuthenticationHeadersResponse

// NewPublicDebugAuthenticationHeadersResponse instantiates a new PublicDebugAuthenticationHeadersResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPublicDebugAuthenticationHeadersResponse(xRhIdentityPresent bool, xPulpVpnVerified bool, xPulpVpnAccessPresent bool) *PublicDebugAuthenticationHeadersResponse {
	this := PublicDebugAuthenticationHeadersResponse{}
	this.XRhIdentityPresent = xRhIdentityPresent
	this.XPulpVpnVerified = xPulpVpnVerified
	this.XPulpVpnAccessPresent = xPulpVpnAccessPresent
	return &this
}

// NewPublicDebugAuthenticationHeadersResponseWithDefaults instantiates a new PublicDebugAuthenticationHeadersResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPublicDebugAuthenticationHeadersResponseWithDefaults() *PublicDebugAuthenticationHeadersResponse {
	this := PublicDebugAuthenticationHeadersResponse{}
	return &this
}

// GetXRhIdentityPresent returns the XRhIdentityPresent field value
func (o *PublicDebugAuthenticationHeadersResponse) GetXRhIdentityPresent() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.XRhIdentityPresent
}

// GetXRhIdentityPresentOk returns a tuple with the XRhIdentityPresent field value
// and a boolean to check if the value has been set.
func (o *PublicDebugAuthenticationHeadersResponse) GetXRhIdentityPresentOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.XRhIdentityPresent, true
}

// SetXRhIdentityPresent sets field value
func (o *PublicDebugAuthenticationHeadersResponse) SetXRhIdentityPresent(v bool) {
	o.XRhIdentityPresent = v
}

// GetXPulpVpnVerified returns the XPulpVpnVerified field value
func (o *PublicDebugAuthenticationHeadersResponse) GetXPulpVpnVerified() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.XPulpVpnVerified
}

// GetXPulpVpnVerifiedOk returns a tuple with the XPulpVpnVerified field value
// and a boolean to check if the value has been set.
func (o *PublicDebugAuthenticationHeadersResponse) GetXPulpVpnVerifiedOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.XPulpVpnVerified, true
}

// SetXPulpVpnVerified sets field value
func (o *PublicDebugAuthenticationHeadersResponse) SetXPulpVpnVerified(v bool) {
	o.XPulpVpnVerified = v
}

// GetXPulpVpnAccessPresent returns the XPulpVpnAccessPresent field value
func (o *PublicDebugAuthenticationHeadersResponse) GetXPulpVpnAccessPresent() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.XPulpVpnAccessPresent
}

// GetXPulpVpnAccessPresentOk returns a tuple with the XPulpVpnAccessPresent field value
// and a boolean to check if the value has been set.
func (o *PublicDebugAuthenticationHeadersResponse) GetXPulpVpnAccessPresentOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.XPulpVpnAccessPresent, true
}

// SetXPulpVpnAccessPresent sets field value
func (o *PublicDebugAuthenticationHeadersResponse) SetXPulpVpnAccessPresent(v bool) {
	o.XPulpVpnAccessPresent = v
}

func (o PublicDebugAuthenticationHeadersResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PublicDebugAuthenticationHeadersResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["x_rh_identity_present"] = o.XRhIdentityPresent
	toSerialize["x_pulp_vpn_verified"] = o.XPulpVpnVerified
	toSerialize["x_pulp_vpn_access_present"] = o.XPulpVpnAccessPresent

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *PublicDebugAuthenticationHeadersResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"x_rh_identity_present",
		"x_pulp_vpn_verified",
		"x_pulp_vpn_access_present",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varPublicDebugAuthenticationHeadersResponse := _PublicDebugAuthenticationHeadersResponse{}

	err = json.Unmarshal(data, &varPublicDebugAuthenticationHeadersResponse)

	if err != nil {
		return err
	}

	*o = PublicDebugAuthenticationHeadersResponse(varPublicDebugAuthenticationHeadersResponse)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "x_rh_identity_present")
		delete(additionalProperties, "x_pulp_vpn_verified")
		delete(additionalProperties, "x_pulp_vpn_access_present")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullablePublicDebugAuthenticationHeadersResponse struct {
	value *PublicDebugAuthenticationHeadersResponse
	isSet bool
}

func (v NullablePublicDebugAuthenticationHeadersResponse) Get() *PublicDebugAuthenticationHeadersResponse {
	return v.value
}

func (v *NullablePublicDebugAuthenticationHeadersResponse) Set(val *PublicDebugAuthenticationHeadersResponse) {
	v.value = val
	v.isSet = true
}

func (v NullablePublicDebugAuthenticationHeadersResponse) IsSet() bool {
	return v.isSet
}

func (v *NullablePublicDebugAuthenticationHeadersResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePublicDebugAuthenticationHeadersResponse(val *PublicDebugAuthenticationHeadersResponse) *NullablePublicDebugAuthenticationHeadersResponse {
	return &NullablePublicDebugAuthenticationHeadersResponse{value: val, isSet: true}
}

func (v NullablePublicDebugAuthenticationHeadersResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePublicDebugAuthenticationHeadersResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


